/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BoardFilter } from "../models/BoardFilter";
import { boardFilterCreatedAtSchema } from "./boardFilterCreatedAtSchema";
import { boardFilterIdSchema } from "./boardFilterIdSchema";
import { boardFilterOwnerIdSchema } from "./boardFilterOwnerIdSchema";
import { boardFilterUpdatedAtSchema } from "./boardFilterUpdatedAtSchema";
import { boardFilterVisibilitySchema } from "./boardFilterVisibilitySchema";
import { todoFilterSchema } from "./todoFilterSchema";
import { z } from "zod/v4";

/**
 * @description Filters the query to results matching the given filter object
 */
export const boardFilterSchema = z
  .object({
    get and() {
      return z
        .array(
          boardFilterSchema.describe(
            "Filters the query to results matching the given filter object",
          ),
        )
        .refine((items) => new Set(items).size === items.length, {
          message: "Array entries must be unique",
        })
        .optional();
    },
    get created_at() {
      return boardFilterCreatedAtSchema.optional();
    },
    get id() {
      return boardFilterIdSchema.optional();
    },
    get not() {
      return boardFilterSchema
        .describe("Filters the query to results matching the given filter object")
        .optional();
    },
    get or() {
      return z
        .array(
          boardFilterSchema.describe(
            "Filters the query to results matching the given filter object",
          ),
        )
        .refine((items) => new Set(items).size === items.length, {
          message: "Array entries must be unique",
        })
        .optional();
    },
    get owner_id() {
      return boardFilterOwnerIdSchema.optional();
    },
    get todos() {
      return todoFilterSchema
        .describe("Filters the query to results matching the given filter object")
        .optional();
    },
    get updated_at() {
      return boardFilterUpdatedAtSchema.optional();
    },
    get visibility() {
      return boardFilterVisibilitySchema.optional();
    },
  })
  .describe(
    "Filters the query to results matching the given filter object",
  ) as unknown as z.ZodType<BoardFilter>;
