/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BoardFilterVisibility } from "../models/BoardFilterVisibility";
import { z } from "zod/v4";

export const boardFilterVisibilitySchema = z.object({
  eq: z.optional(z.enum(["private", "public"])),
  greater_than: z.optional(z.enum(["private", "public"])),
  greater_than_or_equal: z.optional(z.enum(["private", "public"])),
  in: z.optional(z.array(z.enum(["private", "public"]))),
  is_distinct_from: z.optional(z.string()),
  is_nil: z.optional(z.boolean()),
  is_not_distinct_from: z.optional(z.string()),
  less_than: z.optional(z.enum(["private", "public"])),
  less_than_or_equal: z.optional(z.enum(["private", "public"])),
  not_eq: z.optional(z.enum(["private", "public"])),
}) as unknown as z.ZodType<BoardFilterVisibility>;
