/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Board } from "../models/Board";
import { z } from "zod/v4";

/**
 * @description A \"Resource object\" representing a board
 */
export const boardSchema = z
  .object({
    attributes: z.optional(
      z
        .object({
          created_at: z.any().describe("Field included by default."),
          owner_id: z.uuid().describe("Field included by default."),
          updated_at: z.any().describe("Field included by default."),
          visibility: z
            .enum(["private", "public"])
            .describe("Field included by default."),
        })
        .describe("An attributes object for a board"),
    ),
    id: z.string(),
    relationships: z.optional(
      z
        .object({
          owner: z.optional(
            z.object({
              data: z
                .object({
                  id: z.string(),
                  meta: z.optional(z.object({}).catchall(z.any())),
                  type: z.string(),
                })
                .describe("An identifier for owner")
                .nullish(),
            }),
          ),
          todos: z.optional(
            z.object({
              data: z.optional(
                z
                  .array(
                    z
                      .object({
                        id: z.string(),
                        meta: z.optional(z.object({}).catchall(z.any())),
                        type: z.string(),
                      })
                      .describe("Resource identifiers for todos"),
                  )
                  .refine((items) => new Set(items).size === items.length, {
                    message: "Array entries must be unique",
                  })
                  .describe("Relationship data for todos"),
              ),
            }),
          ),
        })
        .describe("A relationships object for a board"),
    ),
    type: z.string(),
  })
  .describe(
    'A "Resource object" representing a board',
  ) as unknown as z.ZodType<Board>;
