/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BoardFilterUpdatedAt } from "../models/BoardFilterUpdatedAt";
import { z } from "zod/v4";

export const boardFilterUpdatedAtSchema = z.object({
  eq: z.optional(z.any()),
  greater_than: z.optional(z.any()),
  greater_than_or_equal: z.optional(z.any()),
  in: z.optional(z.array(z.any())),
  is_distinct_from: z.optional(z.string()),
  is_nil: z.optional(z.boolean()),
  is_not_distinct_from: z.optional(z.string()),
  less_than: z.optional(z.any()),
  less_than_or_equal: z.optional(z.any()),
  not_eq: z.optional(z.any()),
}) as unknown as z.ZodType<BoardFilterUpdatedAt>;
