/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  DeleteTodosId200,
  DeleteTodosIdError,
  DeleteTodosIdMutationResponse,
  DeleteTodosIdPathParams,
  DeleteTodosIdQueryParams,
} from "../models/DeleteTodosId";
import { errorsSchema } from "./errorsSchema";
import { z } from "zod/v4";

export const deleteTodosIdPathParamsSchema = z.object({
  id: z.string(),
}) as unknown as z.ZodType<DeleteTodosIdPathParams>;

export const deleteTodosIdQueryParamsSchema = z
  .object({
    include: z.optional(
      z
        .string()
        .regex(/^(user)(,(user))*$/)
        .describe("Relationship paths to include in the response"),
    ),
    fields: z.optional(
      z
        .object({
          todo: z.optional(
            z.string().describe("Comma separated field names for todo"),
          ),
        })
        .catchall(z.any())
        .describe(
          "Limits the response fields to only those listed for each type",
        ),
    ),
  })
  .optional() as unknown as z.ZodType<DeleteTodosIdQueryParams>;

/**
 * @description Deleted successfully
 */
export const deleteTodosId200Schema =
  z.any() as unknown as z.ZodType<DeleteTodosId200>;

/**
 * @description General Error
 */
export const deleteTodosIdErrorSchema = z.lazy(
  () => errorsSchema,
) as unknown as z.ZodType<DeleteTodosIdError>;

export const deleteTodosIdMutationResponseSchema = z.lazy(
  () => deleteTodosId200Schema,
) as unknown as z.ZodType<DeleteTodosIdMutationResponse>;
