/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  DeleteTodosId200,
  DeleteTodosIdError,
  DeleteTodosIdMutationResponse,
  DeleteTodosIdPathParams,
  DeleteTodosIdQueryParams,
} from "../models/DeleteTodosId";
import { errorsSchema } from "./errorsSchema";
import { z } from "zod/v4";

export const deleteTodosIdPathParamsSchema = z.object({
  id: z.string(),
}) as unknown as z.ZodType<DeleteTodosIdPathParams>;

export const deleteTodosIdQueryParamsSchema = z
  .object({
    include: z.optional(
      z.array(z.enum(["board"])).describe("Relationship paths to include in the response"),
    ),
    fields: z.optional(
      z
        .object({
          board: z.optional(
            z
              .array(
                z.enum([
                  "id",
                  "visibility",
                  "created_at",
                  "updated_at",
                  "owner_id",
                  "owner",
                  "todos",
                ]),
              )
              .describe("Field names for board"),
          ),
          todo: z.optional(
            z
              .array(
                z.enum([
                  "id",
                  "title",
                  "content",
                  "status",
                  "priority",
                  "created_at",
                  "updated_at",
                  "board_id",
                  "board",
                ]),
              )
              .describe("Field names for todo"),
          ),
          user: z.optional(
            z
              .array(z.enum(["id", "email", "name", "board", "identities"]))
              .describe("Field names for user"),
          ),
        })
        .describe("Limits the response fields to only those listed for each type"),
    ),
  })
  .optional() as unknown as z.ZodType<DeleteTodosIdQueryParams>;

/**
 * @description Deleted successfully
 */
export const deleteTodosId200Schema = z.any() as unknown as z.ZodType<DeleteTodosId200>;

/**
 * @description General Error
 */
export const deleteTodosIdErrorSchema = z.lazy(
  () => errorsSchema,
) as unknown as z.ZodType<DeleteTodosIdError>;

export const deleteTodosIdMutationResponseSchema = z.lazy(
  () => deleteTodosId200Schema,
) as unknown as z.ZodType<DeleteTodosIdMutationResponse>;
