/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Errors } from "../models/Errors";
import { errorSchema } from "./errorSchema";
import { z } from "zod/v4";

export const errorsSchema = z
  .array(z.lazy(() => errorSchema))
  .refine((items) => new Set(items).size === items.length, {
    message: "Array entries must be unique",
  }) as unknown as z.ZodType<Errors>;
