/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Error } from "../models/Error";
import { linksSchema } from "./linksSchema";
import { z } from "zod/v4";

export const errorSchema = z.object({
  code: z.optional(
    z.string().describe("An application-specific error code, expressed as a string value."),
  ),
  detail: z.optional(
    z.string().describe("A human-readable explanation specific to this occurrence of the problem."),
  ),
  id: z.optional(
    z.string().describe("A unique identifier for this particular occurrence of the problem."),
  ),
  get links() {
    return linksSchema.optional();
  },
  source: z.optional(
    z.object({
      parameter: z.optional(
        z.string().describe("A string indicating which query parameter caused the error."),
      ),
      pointer: z.optional(
        z
          .string()
          .describe(
            'A JSON Pointer [RFC6901] to the associated entity in the request document [e.g. "/data" for a primary data object, or "/data/attributes/title" for a specific attribute].',
          ),
      ),
    }),
  ),
  status: z.optional(
    z
      .string()
      .describe("The HTTP status code applicable to this problem, expressed as a string value."),
  ),
  title: z.optional(
    z
      .string()
      .describe(
        "A short, human-readable summary of the problem. It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.",
      ),
  ),
}) as unknown as z.ZodType<Error>;
