/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetBoardsId200,
  GetBoardsIdError,
  GetBoardsIdPathParams,
  GetBoardsIdQueryParams,
  GetBoardsIdQueryResponse,
} from "../models/GetBoardsId";
import { boardSchema } from "./boardSchema";
import { errorsSchema } from "./errorsSchema";
import { userSchema } from "./userSchema";
import { z } from "zod/v4";

export const getBoardsIdPathParamsSchema = z.object({
  id: z.string(),
}) as unknown as z.ZodType<GetBoardsIdPathParams>;

export const getBoardsIdQueryParamsSchema = z
  .object({
    include: z.optional(
      z
        .string()
        .regex(/^(owner)(,(owner))*$/)
        .describe("Relationship paths to include in the response"),
    ),
    fields: z.optional(
      z
        .object({
          board: z.optional(
            z.string().describe("Comma separated field names for board"),
          ),
        })
        .catchall(z.any())
        .describe(
          "Limits the response fields to only those listed for each type",
        ),
    ),
  })
  .optional() as unknown as z.ZodType<GetBoardsIdQueryParams>;

/**
 * @description Success
 */
export const getBoardsId200Schema = z.object({
  get data() {
    return boardSchema
      .describe('A "Resource object" representing a board')
      .optional();
  },
  get included() {
    return z
      .array(userSchema)
      .refine((items) => new Set(items).size === items.length, {
        message: "Array entries must be unique",
      })
      .optional();
  },
  meta: z.optional(z.object({}).catchall(z.any())),
}) as unknown as z.ZodType<GetBoardsId200>;

/**
 * @description General Error
 */
export const getBoardsIdErrorSchema = z.lazy(
  () => errorsSchema,
) as unknown as z.ZodType<GetBoardsIdError>;

export const getBoardsIdQueryResponseSchema = z.lazy(
  () => getBoardsId200Schema,
) as unknown as z.ZodType<GetBoardsIdQueryResponse>;
