/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetBoards200,
  GetBoardsError,
  GetBoardsQueryParams,
  GetBoardsQueryResponse,
} from "../models/GetBoards";
import { boardFilterSchema } from "./boardFilterSchema";
import { boardSchema } from "./boardSchema";
import { errorsSchema } from "./errorsSchema";
import { userSchema } from "./userSchema";
import { z } from "zod/v4";

export const getBoardsQueryParamsSchema = z
  .object({
    get filter() {
      return boardFilterSchema
        .describe(
          "Filters the query to results matching the given filter object",
        )
        .optional();
    },
    sort: z.optional(
      z
        .string()
        .regex(
          /^(id|-id|\+\+id|--id|visibility|-visibility|\+\+visibility|--visibility|created_at|-created_at|\+\+created_at|--created_at|updated_at|-updated_at|\+\+updated_at|--updated_at|owner_id|-owner_id|\+\+owner_id|--owner_id)(,(id|-id|\+\+id|--id|visibility|-visibility|\+\+visibility|--visibility|created_at|-created_at|\+\+created_at|--created_at|updated_at|-updated_at|\+\+updated_at|--updated_at|owner_id|-owner_id|\+\+owner_id|--owner_id))*$/,
        )
        .describe("Sort order to apply to the results"),
    ),
    page: z.optional(
      z
        .object({
          after: z.optional(z.string()),
          before: z.optional(z.string()),
          count: z.optional(z.boolean().default(false)),
          limit: z.optional(z.coerce.number().int().min(1)),
          offset: z.optional(z.coerce.number().int().min(0)),
        })
        .describe(
          "Paginates the response with the limit and offset or keyset pagination.",
        ),
    ),
    include: z.optional(
      z
        .string()
        .regex(/^(owner)(,(owner))*$/)
        .describe("Relationship paths to include in the response"),
    ),
    fields: z.optional(
      z
        .object({
          board: z.optional(
            z.string().describe("Comma separated field names for board"),
          ),
        })
        .catchall(z.any())
        .describe(
          "Limits the response fields to only those listed for each type",
        ),
    ),
  })
  .optional() as unknown as z.ZodType<GetBoardsQueryParams>;

/**
 * @description Success
 */
export const getBoards200Schema = z.object({
  get data() {
    return z
      .array(boardSchema.describe('A "Resource object" representing a board'))
      .refine((items) => new Set(items).size === items.length, {
        message: "Array entries must be unique",
      })
      .describe("An array of resource objects representing a board")
      .optional();
  },
  get included() {
    return z
      .array(userSchema)
      .refine((items) => new Set(items).size === items.length, {
        message: "Array entries must be unique",
      })
      .optional();
  },
  meta: z.optional(z.object({}).catchall(z.any())),
}) as unknown as z.ZodType<GetBoards200>;

/**
 * @description General Error
 */
export const getBoardsErrorSchema = z.lazy(
  () => errorsSchema,
) as unknown as z.ZodType<GetBoardsError>;

export const getBoardsQueryResponseSchema = z.lazy(
  () => getBoards200Schema,
) as unknown as z.ZodType<GetBoardsQueryResponse>;
