/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetTodos200,
  GetTodosError,
  GetTodosQueryParams,
  GetTodosQueryResponse,
} from "../models/GetTodos";
import { boardSchema } from "./boardSchema";
import { errorsSchema } from "./errorsSchema";
import { todoFilterSchema } from "./todoFilterSchema";
import { todoSchema } from "./todoSchema";
import { z } from "zod/v4";

export const getTodosQueryParamsSchema = z
  .object({
    get filter() {
      return todoFilterSchema
        .describe("Filters the query to results matching the given filter object")
        .optional();
    },
    sort: z.optional(
      z
        .array(
          z.enum([
            "id",
            "-id",
            "title",
            "-title",
            "content",
            "-content",
            "status",
            "-status",
            "priority",
            "-priority",
            "created_at",
            "-created_at",
            "updated_at",
            "-updated_at",
            "board_id",
            "-board_id",
          ]),
        )
        .describe("Sort order to apply to the results"),
    ),
    page: z.optional(
      z
        .object({
          after: z.optional(z.string()),
          before: z.optional(z.string()),
          count: z.optional(z.boolean().default(false)),
          limit: z.optional(z.coerce.number().int().min(1)),
          offset: z.optional(z.coerce.number().int().min(0)),
        })
        .describe("Paginates the response with the limit and offset or keyset pagination."),
    ),
    include: z.optional(
      z.array(z.enum(["board"])).describe("Relationship paths to include in the response"),
    ),
    fields: z.optional(
      z
        .object({
          board: z.optional(
            z
              .array(
                z.enum([
                  "id",
                  "visibility",
                  "created_at",
                  "updated_at",
                  "owner_id",
                  "owner",
                  "todos",
                ]),
              )
              .describe("Field names for board"),
          ),
          todo: z.optional(
            z
              .array(
                z.enum([
                  "id",
                  "title",
                  "content",
                  "status",
                  "priority",
                  "created_at",
                  "updated_at",
                  "board_id",
                  "board",
                ]),
              )
              .describe("Field names for todo"),
          ),
          user: z.optional(
            z
              .array(z.enum(["id", "email", "name", "board", "identities"]))
              .describe("Field names for user"),
          ),
        })
        .describe("Limits the response fields to only those listed for each type"),
    ),
  })
  .optional() as unknown as z.ZodType<GetTodosQueryParams>;

/**
 * @description Success
 */
export const getTodos200Schema = z.object({
  get data() {
    return z
      .array(todoSchema.describe('A "Resource object" representing a todo'))
      .refine((items) => new Set(items).size === items.length, {
        message: "Array entries must be unique",
      })
      .describe("An array of resource objects representing a todo")
      .optional();
  },
  get included() {
    return z
      .array(boardSchema)
      .refine((items) => new Set(items).size === items.length, {
        message: "Array entries must be unique",
      })
      .optional();
  },
  meta: z.optional(
    z
      .object({
        statuses: z.optional(
          z.array(z.enum(["blocked", "backlog", "in_progress", "review", "done", "rejected"])),
        ),
      })
      .catchall(z.any()),
  ),
}) as unknown as z.ZodType<GetTodos200>;

/**
 * @description General Error
 */
export const getTodosErrorSchema = z.lazy(
  () => errorsSchema,
) as unknown as z.ZodType<GetTodosError>;

export const getTodosQueryResponseSchema = z.lazy(
  () => getTodos200Schema,
) as unknown as z.ZodType<GetTodosQueryResponse>;
