/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetTodosId200,
  GetTodosIdError,
  GetTodosIdPathParams,
  GetTodosIdQueryParams,
  GetTodosIdQueryResponse,
} from "../models/GetTodosId";
import { boardSchema } from "./boardSchema";
import { errorsSchema } from "./errorsSchema";
import { todoSchema } from "./todoSchema";
import { z } from "zod/v4";

export const getTodosIdPathParamsSchema = z.object({
  id: z.string(),
}) as unknown as z.ZodType<GetTodosIdPathParams>;

export const getTodosIdQueryParamsSchema = z
  .object({
    include: z.optional(
      z.array(z.enum(["board"])).describe("Relationship paths to include in the response"),
    ),
    fields: z.optional(
      z
        .object({
          board: z.optional(
            z
              .array(
                z.enum([
                  "id",
                  "visibility",
                  "created_at",
                  "updated_at",
                  "owner_id",
                  "owner",
                  "todos",
                ]),
              )
              .describe("Field names for board"),
          ),
          todo: z.optional(
            z
              .array(
                z.enum([
                  "id",
                  "title",
                  "content",
                  "status",
                  "priority",
                  "created_at",
                  "updated_at",
                  "board_id",
                  "board",
                ]),
              )
              .describe("Field names for todo"),
          ),
          user: z.optional(
            z
              .array(z.enum(["id", "email", "name", "board", "identities"]))
              .describe("Field names for user"),
          ),
        })
        .describe("Limits the response fields to only those listed for each type"),
    ),
  })
  .optional() as unknown as z.ZodType<GetTodosIdQueryParams>;

/**
 * @description Success
 */
export const getTodosId200Schema = z.object({
  get data() {
    return todoSchema.describe('A "Resource object" representing a todo').optional();
  },
  get included() {
    return z
      .array(boardSchema)
      .refine((items) => new Set(items).size === items.length, {
        message: "Array entries must be unique",
      })
      .optional();
  },
  meta: z.optional(z.object({}).catchall(z.any())),
}) as unknown as z.ZodType<GetTodosId200>;

/**
 * @description General Error
 */
export const getTodosIdErrorSchema = z.lazy(
  () => errorsSchema,
) as unknown as z.ZodType<GetTodosIdError>;

export const getTodosIdQueryResponseSchema = z.lazy(
  () => getTodosId200Schema,
) as unknown as z.ZodType<GetTodosIdQueryResponse>;
