/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Links } from "../models/Links";
import { linkSchema } from "./linkSchema";
import { z } from "zod/v4";

export const linksSchema = z
  .object({})
  .catchall(
    z
      .lazy(() => linkSchema)
      .describe(
        "A link MUST be represented as either: a string containing the link's URL or a link object.",
      ),
  ) as unknown as z.ZodType<Links>;
