/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PatchBoardsId200,
  PatchBoardsIdError,
  PatchBoardsIdMutationRequest,
  PatchBoardsIdMutationResponse,
  PatchBoardsIdPathParams,
  PatchBoardsIdQueryParams,
} from "../models/PatchBoardsId";
import { boardSchema } from "./boardSchema";
import { errorsSchema } from "./errorsSchema";
import { userSchema } from "./userSchema";
import { z } from "zod/v4";

export const patchBoardsIdPathParamsSchema = z.object({
  id: z.string(),
}) as unknown as z.ZodType<PatchBoardsIdPathParams>;

export const patchBoardsIdQueryParamsSchema = z
  .object({
    include: z.optional(
      z
        .string()
        .regex(/^(owner)(,(owner))*$/)
        .describe("Relationship paths to include in the response"),
    ),
    fields: z.optional(
      z
        .object({
          board: z.optional(
            z.string().describe("Comma separated field names for board"),
          ),
        })
        .catchall(z.any())
        .describe(
          "Limits the response fields to only those listed for each type",
        ),
    ),
  })
  .optional() as unknown as z.ZodType<PatchBoardsIdQueryParams>;

/**
 * @description Success
 */
export const patchBoardsId200Schema = z.object({
  get data() {
    return boardSchema
      .describe('A "Resource object" representing a board')
      .optional();
  },
  get included() {
    return z
      .array(userSchema)
      .refine((items) => new Set(items).size === items.length, {
        message: "Array entries must be unique",
      })
      .optional();
  },
  meta: z.optional(z.object({}).catchall(z.any())),
}) as unknown as z.ZodType<PatchBoardsId200>;

/**
 * @description General Error
 */
export const patchBoardsIdErrorSchema = z.lazy(
  () => errorsSchema,
) as unknown as z.ZodType<PatchBoardsIdError>;

/**
 * @description Request body for the /boards/:id operation on board resource
 */
export const patchBoardsIdMutationRequestSchema = z.object({
  data: z.object({
    attributes: z.optional(
      z.object({
        visibility: z.optional(
          z.union([z.enum(["private", "public"]), z.null()]),
        ),
      }),
    ),
    id: z.string(),
    relationships: z.optional(z.object({})),
    type: z.optional(z.enum(["board"])),
  }),
}) as unknown as z.ZodType<PatchBoardsIdMutationRequest>;

export const patchBoardsIdMutationResponseSchema = z.lazy(
  () => patchBoardsId200Schema,
) as unknown as z.ZodType<PatchBoardsIdMutationResponse>;
