/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PatchTodosId200,
  PatchTodosIdError,
  PatchTodosIdMutationRequest,
  PatchTodosIdMutationResponse,
  PatchTodosIdPathParams,
  PatchTodosIdQueryParams,
} from "../models/PatchTodosId";
import { boardSchema } from "./boardSchema";
import { errorsSchema } from "./errorsSchema";
import { todoSchema } from "./todoSchema";
import { z } from "zod/v4";

export const patchTodosIdPathParamsSchema = z.object({
  id: z.string(),
}) as unknown as z.ZodType<PatchTodosIdPathParams>;

export const patchTodosIdQueryParamsSchema = z
  .object({
    include: z.optional(
      z
        .string()
        .regex(/^(board)(,(board))*$/)
        .describe("Relationship paths to include in the response"),
    ),
    fields: z.optional(
      z
        .object({
          todo: z.optional(
            z.string().describe("Comma separated field names for todo"),
          ),
        })
        .catchall(z.any())
        .describe(
          "Limits the response fields to only those listed for each type",
        ),
    ),
  })
  .optional() as unknown as z.ZodType<PatchTodosIdQueryParams>;

/**
 * @description Success
 */
export const patchTodosId200Schema = z.object({
  get data() {
    return todoSchema
      .describe('A "Resource object" representing a todo')
      .optional();
  },
  get included() {
    return z
      .array(boardSchema)
      .refine((items) => new Set(items).size === items.length, {
        message: "Array entries must be unique",
      })
      .optional();
  },
  meta: z.optional(z.object({}).catchall(z.any())),
}) as unknown as z.ZodType<PatchTodosId200>;

/**
 * @description General Error
 */
export const patchTodosIdErrorSchema = z.lazy(
  () => errorsSchema,
) as unknown as z.ZodType<PatchTodosIdError>;

/**
 * @description Request body for the /todos/:id operation on todo resource
 */
export const patchTodosIdMutationRequestSchema = z.object({
  data: z.object({
    attributes: z.optional(
      z.object({
        content: z.optional(z.union([z.string(), z.null()])),
        priority: z.optional(
          z.union([z.enum(["low", "medium", "high", "urgent"]), z.null()]),
        ),
        status: z.optional(
          z.union([
            z.enum([
              "blocked",
              "backlog",
              "in_progress",
              "review",
              "done",
              "rejected",
            ]),
            z.null(),
          ]),
        ),
        title: z.optional(z.union([z.string(), z.null()])),
      }),
    ),
    id: z.string(),
    relationships: z.optional(z.object({})),
    type: z.optional(z.enum(["todo"])),
  }),
}) as unknown as z.ZodType<PatchTodosIdMutationRequest>;

export const patchTodosIdMutationResponseSchema = z.lazy(
  () => patchTodosId200Schema,
) as unknown as z.ZodType<PatchTodosIdMutationResponse>;
