/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PostTodos201,
  PostTodosError,
  PostTodosMutationRequest,
  PostTodosMutationResponse,
  PostTodosQueryParams,
} from "../models/PostTodos";
import { boardSchema } from "./boardSchema";
import { errorsSchema } from "./errorsSchema";
import { todoSchema } from "./todoSchema";
import { z } from "zod/v4";

export const postTodosQueryParamsSchema = z
  .object({
    include: z.optional(
      z
        .string()
        .regex(/^(board)(,(board))*$/)
        .describe("Relationship paths to include in the response"),
    ),
    fields: z.optional(
      z
        .object({
          todo: z.optional(
            z.string().describe("Comma separated field names for todo"),
          ),
        })
        .catchall(z.any())
        .describe(
          "Limits the response fields to only those listed for each type",
        ),
    ),
  })
  .optional() as unknown as z.ZodType<PostTodosQueryParams>;

/**
 * @description Success
 */
export const postTodos201Schema = z.object({
  get data() {
    return todoSchema
      .describe('A "Resource object" representing a todo')
      .optional();
  },
  get included() {
    return z
      .array(boardSchema)
      .refine((items) => new Set(items).size === items.length, {
        message: "Array entries must be unique",
      })
      .optional();
  },
  meta: z.optional(z.object({}).catchall(z.any())),
}) as unknown as z.ZodType<PostTodos201>;

/**
 * @description General Error
 */
export const postTodosErrorSchema = z.lazy(
  () => errorsSchema,
) as unknown as z.ZodType<PostTodosError>;

/**
 * @description Request body for the /todos operation on todo resource
 */
export const postTodosMutationRequestSchema = z.object({
  data: z.object({
    attributes: z.optional(
      z.object({
        board_id: z.uuid(),
        content: z.string(),
        priority: z.optional(
          z.union([z.enum(["low", "medium", "high", "urgent"]), z.null()]),
        ),
        status: z.optional(
          z.union([
            z.enum([
              "blocked",
              "backlog",
              "in_progress",
              "review",
              "done",
              "rejected",
            ]),
            z.null(),
          ]),
        ),
        title: z.string(),
      }),
    ),
    relationships: z.optional(z.object({})),
    type: z.optional(z.enum(["todo"])),
  }),
}) as unknown as z.ZodType<PostTodosMutationRequest>;

export const postTodosMutationResponseSchema = z.lazy(
  () => postTodos201Schema,
) as unknown as z.ZodType<PostTodosMutationResponse>;
