/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TodoFilterStatus } from "../models/TodoFilterStatus";
import { z } from "zod/v4";

export const todoFilterStatusSchema = z.object({
  eq: z.optional(z.enum(["blocked", "backlog", "in_progress", "review", "done", "rejected"])),
  greater_than: z.optional(
    z.enum(["blocked", "backlog", "in_progress", "review", "done", "rejected"]),
  ),
  greater_than_or_equal: z.optional(
    z.enum(["blocked", "backlog", "in_progress", "review", "done", "rejected"]),
  ),
  in: z.optional(
    z.array(z.enum(["blocked", "backlog", "in_progress", "review", "done", "rejected"])),
  ),
  is_distinct_from: z.optional(z.string()),
  is_nil: z.optional(z.boolean()),
  is_not_distinct_from: z.optional(z.string()),
  less_than: z.optional(
    z.enum(["blocked", "backlog", "in_progress", "review", "done", "rejected"]),
  ),
  less_than_or_equal: z.optional(
    z.enum(["blocked", "backlog", "in_progress", "review", "done", "rejected"]),
  ),
  not_eq: z.optional(z.enum(["blocked", "backlog", "in_progress", "review", "done", "rejected"])),
}) as unknown as z.ZodType<TodoFilterStatus>;
