/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const todoFilterStatusSchema = z.object({
    "eq": z.enum(["blocked", "backlog", "in_progress", "review", "done", "rejected"]).optional(),
"greater_than": z.enum(["blocked", "backlog", "in_progress", "review", "done", "rejected"]).optional(),
"greater_than_or_equal": z.enum(["blocked", "backlog", "in_progress", "review", "done", "rejected"]).optional(),
"in": z.array(z.enum(["blocked", "backlog", "in_progress", "review", "done", "rejected"])).optional(),
"is_distinct_from": z.string().optional(),
"is_nil": z.boolean().optional(),
"is_not_distinct_from": z.string().optional(),
"less_than": z.enum(["blocked", "backlog", "in_progress", "review", "done", "rejected"]).optional(),
"less_than_or_equal": z.enum(["blocked", "backlog", "in_progress", "review", "done", "rejected"]).optional(),
"not_eq": z.enum(["blocked", "backlog", "in_progress", "review", "done", "rejected"]).optional()
    })