/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TodoFilterBoardId } from "../models/TodoFilterBoardId";
import { z } from "zod/v4";

export const todoFilterBoardIdSchema = z.object({
  eq: z.optional(z.uuid()),
  greater_than: z.optional(z.uuid()),
  greater_than_or_equal: z.optional(z.uuid()),
  in: z.optional(z.array(z.uuid())),
  is_distinct_from: z.optional(z.string()),
  is_nil: z.optional(z.boolean()),
  is_not_distinct_from: z.optional(z.string()),
  less_than: z.optional(z.uuid()),
  less_than_or_equal: z.optional(z.uuid()),
  not_eq: z.optional(z.uuid()),
}) as unknown as z.ZodType<TodoFilterBoardId>;
