/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description A \"Resource object\" representing a todo
 */
export const todoSchema = z.object({
    "attributes": z.object({
    "content": z.string().describe("Field included by default."),
"created_at": z.any(),
"priority": z.enum(["low", "medium", "high", "urgent"]).describe("Field included by default."),
"status": z.enum(["todo", "in_progress", "completed"]).describe("Field included by default."),
"title": z.string().describe("Field included by default."),
"updated_at": z.any(),
"user_id": z.uuid().describe("Field included by default.")
    }).describe("An attributes object for a todo").optional(),
"id": z.string(),
"relationships": z.object({
    "user": z.object({
    "data": z.object({
    "id": z.string(),
"meta": z.object({
    
    }).catchall(z.any()).optional(),
"type": z.string()
    }).describe("An identifier for user").nullable().nullish()
    }).optional()
    }).describe("A relationships object for a todo").optional(),
"type": z.string()
    }).describe("A \"Resource object\" representing a todo")