/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Todo } from "../models/Todo";
import { z } from "zod/v4";

/**
 * @description A \"Resource object\" representing a todo
 */
export const todoSchema = z
  .object({
    attributes: z.optional(
      z
        .object({
          content: z.string().describe("Field included by default."),
          created_at: z.any().describe("Field included by default."),
          priority: z
            .enum(["low", "medium", "high", "urgent"])
            .describe("Field included by default."),
          status: z
            .enum([
              "blocked",
              "backlog",
              "in_progress",
              "review",
              "done",
              "rejected",
            ])
            .describe("Field included by default."),
          title: z.string().describe("Field included by default."),
          updated_at: z.any().describe("Field included by default."),
          user_id: z.uuid().describe("Field included by default."),
        })
        .describe("An attributes object for a todo"),
    ),
    id: z.string(),
    relationships: z.optional(
      z
        .object({
          user: z.optional(
            z.object({
              data: z
                .object({
                  id: z.string(),
                  meta: z.optional(z.object({}).catchall(z.any())),
                  type: z.string(),
                })
                .describe("An identifier for user")
                .nullish(),
            }),
          ),
        })
        .describe("A relationships object for a todo"),
    ),
    type: z.string(),
  })
  .describe(
    'A "Resource object" representing a todo',
  ) as unknown as z.ZodType<Todo>;
