/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const todoFilterUpdatedAtSchema = z.object({
    "eq": z.any().optional(),
"greater_than": z.any().optional(),
"greater_than_or_equal": z.any().optional(),
"in": z.array(z.any()).optional(),
"is_distinct_from": z.string().optional(),
"is_nil": z.boolean().optional(),
"is_not_distinct_from": z.string().optional(),
"less_than": z.any().optional(),
"less_than_or_equal": z.any().optional(),
"not_eq": z.any().optional()
    })