/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const todoFilterPrioritySchema = z.object({
    "eq": z.enum(["low", "medium", "high", "urgent"]).optional(),
"greater_than": z.enum(["low", "medium", "high", "urgent"]).optional(),
"greater_than_or_equal": z.enum(["low", "medium", "high", "urgent"]).optional(),
"in": z.array(z.enum(["low", "medium", "high", "urgent"])).optional(),
"is_distinct_from": z.string().optional(),
"is_nil": z.boolean().optional(),
"is_not_distinct_from": z.string().optional(),
"less_than": z.enum(["low", "medium", "high", "urgent"]).optional(),
"less_than_or_equal": z.enum(["low", "medium", "high", "urgent"]).optional(),
"not_eq": z.enum(["low", "medium", "high", "urgent"]).optional()
    })