/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TodoFilter } from "../models/TodoFilter";
import { boardFilterSchema } from "./boardFilterSchema";
import { todoFilterBoardIdSchema } from "./todoFilterBoardIdSchema";
import { todoFilterContentSchema } from "./todoFilterContentSchema";
import { todoFilterCreatedAtSchema } from "./todoFilterCreatedAtSchema";
import { todoFilterIdSchema } from "./todoFilterIdSchema";
import { todoFilterPrioritySchema } from "./todoFilterPrioritySchema";
import { todoFilterStatusSchema } from "./todoFilterStatusSchema";
import { todoFilterTitleSchema } from "./todoFilterTitleSchema";
import { todoFilterUpdatedAtSchema } from "./todoFilterUpdatedAtSchema";
import { z } from "zod/v4";

/**
 * @description Filters the query to results matching the given filter object
 */
export const todoFilterSchema = z
  .object({
    get and() {
      return z
        .array(
          todoFilterSchema.describe(
            "Filters the query to results matching the given filter object",
          ),
        )
        .refine((items) => new Set(items).size === items.length, {
          message: "Array entries must be unique",
        })
        .optional();
    },
    get board() {
      return boardFilterSchema
        .describe(
          "Filters the query to results matching the given filter object",
        )
        .optional();
    },
    get board_id() {
      return todoFilterBoardIdSchema.optional();
    },
    get content() {
      return todoFilterContentSchema.optional();
    },
    get created_at() {
      return todoFilterCreatedAtSchema.optional();
    },
    get id() {
      return todoFilterIdSchema.optional();
    },
    get not() {
      return todoFilterSchema
        .describe(
          "Filters the query to results matching the given filter object",
        )
        .optional();
    },
    get or() {
      return z
        .array(
          todoFilterSchema.describe(
            "Filters the query to results matching the given filter object",
          ),
        )
        .refine((items) => new Set(items).size === items.length, {
          message: "Array entries must be unique",
        })
        .optional();
    },
    get priority() {
      return todoFilterPrioritySchema.optional();
    },
    get status() {
      return todoFilterStatusSchema.optional();
    },
    get title() {
      return todoFilterTitleSchema.optional();
    },
    get updated_at() {
      return todoFilterUpdatedAtSchema.optional();
    },
  })
  .describe(
    "Filters the query to results matching the given filter object",
  ) as unknown as z.ZodType<TodoFilter>;
