/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TodoFilterContent } from "../models/TodoFilterContent";
import { z } from "zod/v4";

export const todoFilterContentSchema = z.object({
  contains: z.optional(z.string()),
  eq: z.optional(z.string()),
  greater_than: z.optional(z.string()),
  greater_than_or_equal: z.optional(z.string()),
  ilike: z.optional(z.string()),
  in: z.optional(z.array(z.string())),
  is_distinct_from: z.optional(z.string()),
  is_nil: z.optional(z.boolean()),
  is_not_distinct_from: z.optional(z.string()),
  less_than: z.optional(z.string()),
  less_than_or_equal: z.optional(z.string()),
  like: z.optional(z.string()),
  not_eq: z.optional(z.string()),
}) as unknown as z.ZodType<TodoFilterContent>;
