/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const todoFilterContentSchema = z.object({
    "contains": z.string().optional(),
"eq": z.string().optional(),
"greater_than": z.string().optional(),
"greater_than_or_equal": z.string().optional(),
"ilike": z.string().optional(),
"in": z.array(z.string()).optional(),
"is_distinct_from": z.string().optional(),
"is_nil": z.boolean().optional(),
"is_not_distinct_from": z.string().optional(),
"less_than": z.string().optional(),
"less_than_or_equal": z.string().optional(),
"like": z.string().optional(),
"not_eq": z.string().optional()
    })