/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from "../models/User";
import { z } from "zod/v4";

/**
 * @description A \"Resource object\" representing a user
 */
export const userSchema = z
  .object({
    attributes: z.optional(
      z
        .object({
          email: z.string().describe("Field included by default."),
          name: z.optional(
            z
              .union([z.string(), z.null()])
              .describe("Field included by default."),
          ),
        })
        .describe("An attributes object for a user"),
    ),
    id: z.string(),
    relationships: z.optional(
      z
        .object({
          todos: z.optional(
            z.object({
              data: z.optional(
                z
                  .array(
                    z
                      .object({
                        id: z.string(),
                        meta: z.optional(z.object({}).catchall(z.any())),
                        type: z.string(),
                      })
                      .describe("Resource identifiers for todos"),
                  )
                  .refine((items) => new Set(items).size === items.length, {
                    message: "Array entries must be unique",
                  })
                  .describe("Relationship data for todos"),
              ),
            }),
          ),
        })
        .describe("A relationships object for a user"),
    ),
    type: z.string(),
  })
  .describe(
    'A "Resource object" representing a user',
  ) as unknown as z.ZodType<User>;
