/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from "../models/User";
import { z } from "zod/v4";

/**
 * @description A \"Resource object\" representing a user
 */
export const userSchema = z
  .object({
    attributes: z.optional(
      z
        .object({
          email: z.string().describe("Field included by default."),
          name: z.optional(
            z
              .union([z.string(), z.null()])
              .describe("Field included by default."),
          ),
        })
        .describe("An attributes object for a user"),
    ),
    id: z.string(),
    relationships: z.optional(
      z
        .object({
          board: z.optional(
            z.object({
              data: z
                .object({
                  id: z.string(),
                  meta: z.optional(z.object({}).catchall(z.any())),
                  type: z.string(),
                })
                .describe("An identifier for board")
                .nullish(),
            }),
          ),
        })
        .describe("A relationships object for a user"),
    ),
    type: z.string(),
  })
  .describe(
    'A "Resource object" representing a user',
  ) as unknown as z.ZodType<User>;
