import "../shared/global.css";
import { Providers } from "../components/providers";
import { EnvironmentProvider } from "../contexts/environment";
import { getEnv } from "../env";

export const metadata = {
  title: "Welcome to nextjs",
  description: "Generated by create-nx-workspace",
};

export default function Layout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  const env = getEnv();
  
  return (
    <html lang="en">
      <body>
        <EnvironmentProvider env={env}>
          <Providers>
            {children}
            {modal}
          </Providers>
        </EnvironmentProvider>
      </body>
    </html>
  );
}
