import "../shared/global.css";
import { Providers } from "../components/providers";
import { Environment } from "../contexts/environment";
import { Suspense } from "react";

export const metadata = {
  title: "Welcome to nextjs",
  description: "Generated by create-nx-workspace",
};

export default function Layout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Environment
          env={{
            PUBLIC_CHANNEL_URL: process.env.PUBLIC_CHANNEL_URL,
          }}
        >
          <Suspense fallback={null}>
            <Providers>
              {children}
              {modal}
            </Providers>
          </Suspense>
        </Environment>
      </body>
    </html>
  );
}
