import "../shared/global.css";
import { SocketProvider } from "../components/socket-provider";

export const metadata = {
  title: "Welcome to nextjs",
  description: "Generated by create-nx-workspace",
};

export default function Layout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SocketProvider>
          {children}
          {modal}
        </SocketProvider>
      </body>
    </html>
  );
}
