/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BoardFilterCreatedAt } from "./BoardFilterCreatedAt";
import type { BoardFilterId } from "./BoardFilterId";
import type { BoardFilterOwnerId } from "./BoardFilterOwnerId";
import type { BoardFilterUpdatedAt } from "./BoardFilterUpdatedAt";
import type { BoardFilterVisibility } from "./BoardFilterVisibility";
import type { TodoFilter } from "./TodoFilter";

/**
 * @description Filters the query to results matching the given filter object
 */
export type BoardFilter = {
  /**
   * @type array | undefined
   */
  and?: BoardFilter[];
  /**
   * @type object | undefined
   */
  created_at?: BoardFilterCreatedAt;
  /**
   * @type object | undefined
   */
  id?: BoardFilterId;
  /**
   * @description Filters the query to results matching the given filter object
   * @type deepObject | undefined
   */
  not?: BoardFilter;
  /**
   * @type array | undefined
   */
  or?: BoardFilter[];
  /**
   * @type object | undefined
   */
  owner_id?: BoardFilterOwnerId;
  /**
   * @description Filters the query to results matching the given filter object
   * @type deepObject | undefined
   */
  todos?: TodoFilter;
  /**
   * @type object | undefined
   */
  updated_at?: BoardFilterUpdatedAt;
  /**
   * @type object | undefined
   */
  visibility?: BoardFilterVisibility;
};
