/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const boardFilterVisibilityEqEnum = {
  private: "private",
  public: "public",
} as const;

export type BoardFilterVisibilityEqEnumKey =
  (typeof boardFilterVisibilityEqEnum)[keyof typeof boardFilterVisibilityEqEnum];

export const boardFilterVisibilityGreaterThanEnum = {
  private: "private",
  public: "public",
} as const;

export type BoardFilterVisibilityGreaterThanEnumKey =
  (typeof boardFilterVisibilityGreaterThanEnum)[keyof typeof boardFilterVisibilityGreaterThanEnum];

export const boardFilterVisibilityGreaterThanOrEqualEnum = {
  private: "private",
  public: "public",
} as const;

export type BoardFilterVisibilityGreaterThanOrEqualEnumKey =
  (typeof boardFilterVisibilityGreaterThanOrEqualEnum)[keyof typeof boardFilterVisibilityGreaterThanOrEqualEnum];

export const boardFilterVisibilityInEnum = {
  private: "private",
  public: "public",
} as const;

export type BoardFilterVisibilityInEnumKey =
  (typeof boardFilterVisibilityInEnum)[keyof typeof boardFilterVisibilityInEnum];

export const boardFilterVisibilityLessThanEnum = {
  private: "private",
  public: "public",
} as const;

export type BoardFilterVisibilityLessThanEnumKey =
  (typeof boardFilterVisibilityLessThanEnum)[keyof typeof boardFilterVisibilityLessThanEnum];

export const boardFilterVisibilityLessThanOrEqualEnum = {
  private: "private",
  public: "public",
} as const;

export type BoardFilterVisibilityLessThanOrEqualEnumKey =
  (typeof boardFilterVisibilityLessThanOrEqualEnum)[keyof typeof boardFilterVisibilityLessThanOrEqualEnum];

export const boardFilterVisibilityNotEqEnum = {
  private: "private",
  public: "public",
} as const;

export type BoardFilterVisibilityNotEqEnumKey =
  (typeof boardFilterVisibilityNotEqEnum)[keyof typeof boardFilterVisibilityNotEqEnum];

export type BoardFilterVisibility = {
  /**
   * @type string | undefined
   */
  eq?: BoardFilterVisibilityEqEnumKey;
  /**
   * @type string | undefined
   */
  greater_than?: BoardFilterVisibilityGreaterThanEnumKey;
  /**
   * @type string | undefined
   */
  greater_than_or_equal?: BoardFilterVisibilityGreaterThanOrEqualEnumKey;
  /**
   * @type array | undefined
   */
  in?: BoardFilterVisibilityInEnumKey[];
  /**
   * @type string | undefined
   */
  is_distinct_from?: string;
  /**
   * @type boolean | undefined
   */
  is_nil?: boolean;
  /**
   * @type string | undefined
   */
  is_not_distinct_from?: string;
  /**
   * @type string | undefined
   */
  less_than?: BoardFilterVisibilityLessThanEnumKey;
  /**
   * @type string | undefined
   */
  less_than_or_equal?: BoardFilterVisibilityLessThanOrEqualEnumKey;
  /**
   * @type string | undefined
   */
  not_eq?: BoardFilterVisibilityNotEqEnumKey;
};
