/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const attributesVisibilityEnum = {
  private: "private",
  public: "public",
} as const;

export type AttributesVisibilityEnumKey =
  (typeof attributesVisibilityEnum)[keyof typeof attributesVisibilityEnum];

/**
 * @description A \"Resource object\" representing a board
 */
export type Board = {
  /**
   * @description An attributes object for a board
   * @type object | undefined
   */
  attributes?: {
    /**
     * @description Field included by default.
     */
    created_at: any;
    /**
     * @description Field included by default.
     * @type string, uuid
     */
    owner_id: string;
    /**
     * @description Field included by default.
     */
    updated_at: any;
    /**
     * @description Field included by default.
     * @type string
     */
    visibility: AttributesVisibilityEnumKey;
  };
  /**
   * @type string
   */
  id: string;
  /**
   * @description A relationships object for a board
   * @type object | undefined
   */
  relationships?: {
    owner?: {
      /**
       * @description An identifier for owner
       * @type object
       */
      data?: {
        /**
         * @type string
         */
        id: string;
        /**
         * @type object | undefined
         */
        meta?: {
          [key: string]: any;
        };
        /**
         * @type string
         */
        type: string;
      } | null;
    };
    todos?: {
      /**
       * @description Relationship data for todos
       * @type array | undefined
       */
      data?: {
        /**
         * @type string
         */
        id: string;
        /**
         * @type object | undefined
         */
        meta?: {
          [key: string]: any;
        };
        /**
         * @type string
         */
        type: string;
      }[];
    };
  };
  /**
   * @type string
   */
  type: string;
};
