/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Board } from "./Board";
import type { BoardFilter } from "./BoardFilter";
import type { Errors } from "./Errors";
import type { User } from "./User";

export const getBoardsQueryParamsSortEnum = {
  id: "id",
  "-id": "-id",
  visibility: "visibility",
  "-visibility": "-visibility",
  created_at: "created_at",
  "-created_at": "-created_at",
  updated_at: "updated_at",
  "-updated_at": "-updated_at",
  owner_id: "owner_id",
  "-owner_id": "-owner_id",
} as const;

export type GetBoardsQueryParamsSortEnumKey =
  (typeof getBoardsQueryParamsSortEnum)[keyof typeof getBoardsQueryParamsSortEnum];

export const getBoardsQueryParamsIncludeEnum = {
  owner: "owner",
} as const;

export type GetBoardsQueryParamsIncludeEnumKey =
  (typeof getBoardsQueryParamsIncludeEnum)[keyof typeof getBoardsQueryParamsIncludeEnum];

export const fieldsBoardEnum = {
  id: "id",
  visibility: "visibility",
  created_at: "created_at",
  updated_at: "updated_at",
  owner_id: "owner_id",
  owner: "owner",
  todos: "todos",
} as const;

export type FieldsBoardEnumKey =
  (typeof fieldsBoardEnum)[keyof typeof fieldsBoardEnum];

export const fieldsTodoEnum = {
  id: "id",
  title: "title",
  content: "content",
  status: "status",
  priority: "priority",
  created_at: "created_at",
  updated_at: "updated_at",
  board_id: "board_id",
  board: "board",
} as const;

export type FieldsTodoEnumKey =
  (typeof fieldsTodoEnum)[keyof typeof fieldsTodoEnum];

export const fieldsUserEnum = {
  id: "id",
  email: "email",
  name: "name",
  board: "board",
  identities: "identities",
} as const;

export type FieldsUserEnumKey =
  (typeof fieldsUserEnum)[keyof typeof fieldsUserEnum];

export type GetBoardsQueryParams = {
  /**
   * @description Filters the query to results matching the given filter object
   * @type deepObject | undefined
   */
  filter?: BoardFilter;
  /**
   * @description Sort order to apply to the results
   * @type array | undefined
   */
  sort?: GetBoardsQueryParamsSortEnumKey[];
  /**
   * @description Paginates the response with the limit and offset or keyset pagination.
   * @type object | undefined
   */
  page?: {
    /**
     * @type string | undefined
     */
    after?: string;
    /**
     * @type string | undefined
     */
    before?: string;
    /**
     * @default false
     * @type boolean | undefined
     */
    count?: boolean;
    /**
     * @minLength 1
     * @type integer | undefined
     */
    limit?: number;
    /**
     * @minLength 0
     * @type integer | undefined
     */
    offset?: number;
  };
  /**
   * @description Relationship paths to include in the response
   * @type array | undefined
   */
  include?: GetBoardsQueryParamsIncludeEnumKey[];
  /**
   * @description Limits the response fields to only those listed for each type
   * @type object | undefined
   */
  fields?: {
    /**
     * @description Field names for board
     * @type array | undefined
     */
    board?: FieldsBoardEnumKey[];
    /**
     * @description Field names for todo
     * @type array | undefined
     */
    todo?: FieldsTodoEnumKey[];
    /**
     * @description Field names for user
     * @type array | undefined
     */
    user?: FieldsUserEnumKey[];
  };
};

/**
 * @description Success
 */
export type GetBoards200 = {
  /**
   * @description An array of resource objects representing a board
   * @type array | undefined
   */
  data?: Board[];
  /**
   * @type array | undefined
   */
  included?: User[];
  /**
   * @type object | undefined
   */
  meta?: {
    [key: string]: any;
  };
};

/**
 * @description General Error
 */
export type GetBoardsError = Errors;

export type GetBoardsQueryResponse = GetBoards200;

export type GetBoardsQuery = {
  Response: GetBoards200;
  QueryParams: GetBoardsQueryParams;
  Errors: any;
};
