/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Board } from "./Board";
import type { Errors } from "./Errors";
import type { User } from "./User";

export type GetBoardsIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

export const getBoardsIdQueryParamsIncludeEnum = {
  owner: "owner",
} as const;

export type GetBoardsIdQueryParamsIncludeEnumKey =
  (typeof getBoardsIdQueryParamsIncludeEnum)[keyof typeof getBoardsIdQueryParamsIncludeEnum];

export const fieldsBoardEnum2 = {
  id: "id",
  visibility: "visibility",
  created_at: "created_at",
  updated_at: "updated_at",
  owner_id: "owner_id",
  owner: "owner",
  todos: "todos",
} as const;

export type FieldsBoardEnum2Key =
  (typeof fieldsBoardEnum2)[keyof typeof fieldsBoardEnum2];

export const fieldsTodoEnum2 = {
  id: "id",
  title: "title",
  content: "content",
  status: "status",
  priority: "priority",
  created_at: "created_at",
  updated_at: "updated_at",
  board_id: "board_id",
  board: "board",
} as const;

export type FieldsTodoEnum2Key =
  (typeof fieldsTodoEnum2)[keyof typeof fieldsTodoEnum2];

export const fieldsUserEnum2 = {
  id: "id",
  email: "email",
  name: "name",
  board: "board",
  identities: "identities",
} as const;

export type FieldsUserEnum2Key =
  (typeof fieldsUserEnum2)[keyof typeof fieldsUserEnum2];

export type GetBoardsIdQueryParams = {
  /**
   * @description Relationship paths to include in the response
   * @type array | undefined
   */
  include?: GetBoardsIdQueryParamsIncludeEnumKey[];
  /**
   * @description Limits the response fields to only those listed for each type
   * @type object | undefined
   */
  fields?: {
    /**
     * @description Field names for board
     * @type array | undefined
     */
    board?: FieldsBoardEnum2Key[];
    /**
     * @description Field names for todo
     * @type array | undefined
     */
    todo?: FieldsTodoEnum2Key[];
    /**
     * @description Field names for user
     * @type array | undefined
     */
    user?: FieldsUserEnum2Key[];
  };
};

/**
 * @description Success
 */
export type GetBoardsId200 = {
  /**
   * @description A \"Resource object\" representing a board
   * @type object | undefined
   */
  data?: Board;
  /**
   * @type array | undefined
   */
  included?: User[];
  /**
   * @type object | undefined
   */
  meta?: {
    [key: string]: any;
  };
};

/**
 * @description General Error
 */
export type GetBoardsIdError = Errors;

export type GetBoardsIdQueryResponse = GetBoardsId200;

export type GetBoardsIdQuery = {
  Response: GetBoardsId200;
  PathParams: GetBoardsIdPathParams;
  QueryParams: GetBoardsIdQueryParams;
  Errors: any;
};
