/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Board } from "./Board";
import type { BoardFilter } from "./BoardFilter";
import type { Errors } from "./Errors";
import type { User } from "./User";

export type GetBoardsQueryParams = {
  /**
   * @description Filters the query to results matching the given filter object
   * @type deepObject | undefined
   */
  filter?: BoardFilter;
  /**
   * @description Sort order to apply to the results
   * @pattern ^(id|-id|\+\+id|--id|visibility|-visibility|\+\+visibility|--visibility|created_at|-created_at|\+\+created_at|--created_at|updated_at|-updated_at|\+\+updated_at|--updated_at|owner_id|-owner_id|\+\+owner_id|--owner_id)(,(id|-id|\+\+id|--id|visibility|-visibility|\+\+visibility|--visibility|created_at|-created_at|\+\+created_at|--created_at|updated_at|-updated_at|\+\+updated_at|--updated_at|owner_id|-owner_id|\+\+owner_id|--owner_id))*$
   * @type string | undefined
   */
  sort?: string;
  /**
   * @description Paginates the response with the limit and offset or keyset pagination.
   * @type object | undefined
   */
  page?: {
    /**
     * @type string | undefined
     */
    after?: string;
    /**
     * @type string | undefined
     */
    before?: string;
    /**
     * @default false
     * @type boolean | undefined
     */
    count?: boolean;
    /**
     * @minLength 1
     * @type integer | undefined
     */
    limit?: number;
    /**
     * @minLength 0
     * @type integer | undefined
     */
    offset?: number;
  };
  /**
   * @description Relationship paths to include in the response
   * @pattern ^(owner)(,(owner))*$
   * @type string | undefined
   */
  include?: string;
  /**
   * @description Limits the response fields to only those listed for each type
   * @type object | undefined
   */
  fields?: {
    /**
     * @description Comma separated field names for board
     * @type string | undefined
     */
    board?: string;
    [key: string]: unknown;
  };
};

/**
 * @description Success
 */
export type GetBoards200 = {
  /**
   * @description An array of resource objects representing a board
   * @type array | undefined
   */
  data?: Board[];
  /**
   * @type array | undefined
   */
  included?: User[];
  /**
   * @type object | undefined
   */
  meta?: {
    [key: string]: any;
  };
};

/**
 * @description General Error
 */
export type GetBoardsError = Errors;

export type GetBoardsQueryResponse = GetBoards200;

export type GetBoardsQuery = {
  Response: GetBoards200;
  QueryParams: GetBoardsQueryParams;
  Errors: any;
};
