/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Board } from "./Board";
import type { Errors } from "./Errors";
import type { User } from "./User";

export type GetBoardsIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

export type GetBoardsIdQueryParams = {
  /**
   * @description Relationship paths to include in the response
   * @pattern ^(owner)(,(owner))*$
   * @type string | undefined
   */
  include?: string;
  /**
   * @description Limits the response fields to only those listed for each type
   * @type object | undefined
   */
  fields?: {
    /**
     * @description Comma separated field names for board
     * @type string | undefined
     */
    board?: string;
    [key: string]: unknown;
  };
};

/**
 * @description Success
 */
export type GetBoardsId200 = {
  /**
   * @description A \"Resource object\" representing a board
   * @type object | undefined
   */
  data?: Board;
  /**
   * @type array | undefined
   */
  included?: User[];
  /**
   * @type object | undefined
   */
  meta?: {
    [key: string]: any;
  };
};

/**
 * @description General Error
 */
export type GetBoardsIdError = Errors;

export type GetBoardsIdQueryResponse = GetBoardsId200;

export type GetBoardsIdQuery = {
  Response: GetBoardsId200;
  PathParams: GetBoardsIdPathParams;
  QueryParams: GetBoardsIdQueryParams;
  Errors: any;
};
