/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Board } from "./Board";
import type { Errors } from "./Errors";
import type { Todo } from "./Todo";
import type { TodoFilter } from "./TodoFilter";

export type GetTodosQueryParams = {
  /**
   * @description Filters the query to results matching the given filter object
   * @type deepObject | undefined
   */
  filter?: TodoFilter;
  /**
   * @description Sort order to apply to the results
   * @pattern ^(id|-id|\+\+id|--id|title|-title|\+\+title|--title|content|-content|\+\+content|--content|status|-status|\+\+status|--status|priority|-priority|\+\+priority|--priority|created_at|-created_at|\+\+created_at|--created_at|updated_at|-updated_at|\+\+updated_at|--updated_at|board_id|-board_id|\+\+board_id|--board_id)(,(id|-id|\+\+id|--id|title|-title|\+\+title|--title|content|-content|\+\+content|--content|status|-status|\+\+status|--status|priority|-priority|\+\+priority|--priority|created_at|-created_at|\+\+created_at|--created_at|updated_at|-updated_at|\+\+updated_at|--updated_at|board_id|-board_id|\+\+board_id|--board_id))*$
   * @type string | undefined
   */
  sort?: string;
  /**
   * @description Paginates the response with the limit and offset or keyset pagination.
   * @type object | undefined
   */
  page?: {
    /**
     * @type string | undefined
     */
    after?: string;
    /**
     * @type string | undefined
     */
    before?: string;
    /**
     * @default false
     * @type boolean | undefined
     */
    count?: boolean;
    /**
     * @minLength 1
     * @type integer | undefined
     */
    limit?: number;
    /**
     * @minLength 0
     * @type integer | undefined
     */
    offset?: number;
  };
  /**
   * @description Relationship paths to include in the response
   * @pattern ^(board)(,(board))*$
   * @type string | undefined
   */
  include?: string;
  /**
   * @description Limits the response fields to only those listed for each type
   * @type object | undefined
   */
  fields?: {
    /**
     * @description Comma separated field names for todo
     * @type string | undefined
     */
    todo?: string;
    [key: string]: unknown;
  };
};

export const metaStatusesEnum = {
  blocked: "blocked",
  backlog: "backlog",
  in_progress: "in_progress",
  review: "review",
  done: "done",
  rejected: "rejected",
} as const;

export type MetaStatusesEnumKey =
  (typeof metaStatusesEnum)[keyof typeof metaStatusesEnum];

/**
 * @description Success
 */
export type GetTodos200 = {
  /**
   * @description An array of resource objects representing a todo
   * @type array | undefined
   */
  data?: Todo[];
  /**
   * @type array | undefined
   */
  included?: Board[];
  /**
   * @type object | undefined
   */
  meta?: {
    /**
     * @type array | undefined
     */
    statuses?: MetaStatusesEnumKey[];
    [key: string]: unknown;
  };
};

/**
 * @description General Error
 */
export type GetTodosError = Errors;

export type GetTodosQueryResponse = GetTodos200;

export type GetTodosQuery = {
  Response: GetTodos200;
  QueryParams: GetTodosQueryParams;
  Errors: any;
};
