/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Board } from "./Board";
import type { Errors } from "./Errors";
import type { Todo } from "./Todo";

export type GetTodosIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

export type GetTodosIdQueryParams = {
  /**
   * @description Relationship paths to include in the response
   * @pattern ^(board)(,(board))*$
   * @type string | undefined
   */
  include?: string;
  /**
   * @description Limits the response fields to only those listed for each type
   * @type object | undefined
   */
  fields?: {
    /**
     * @description Comma separated field names for todo
     * @type string | undefined
     */
    todo?: string;
    [key: string]: unknown;
  };
};

/**
 * @description Success
 */
export type GetTodosId200 = {
  /**
   * @description A \"Resource object\" representing a todo
   * @type object | undefined
   */
  data?: Todo;
  /**
   * @type array | undefined
   */
  included?: Board[];
  /**
   * @type object | undefined
   */
  meta?: {
    [key: string]: any;
  };
};

/**
 * @description General Error
 */
export type GetTodosIdError = Errors;

export type GetTodosIdQueryResponse = GetTodosId200;

export type GetTodosIdQuery = {
  Response: GetTodosId200;
  PathParams: GetTodosIdPathParams;
  QueryParams: GetTodosIdQueryParams;
  Errors: any;
};
