/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Board } from "./Board";
import type { Errors } from "./Errors";
import type { Todo } from "./Todo";
import type { TodoFilter } from "./TodoFilter";

export const getTodosQueryParamsSortEnum = {
  id: "id",
  "-id": "-id",
  title: "title",
  "-title": "-title",
  content: "content",
  "-content": "-content",
  status: "status",
  "-status": "-status",
  priority: "priority",
  "-priority": "-priority",
  created_at: "created_at",
  "-created_at": "-created_at",
  updated_at: "updated_at",
  "-updated_at": "-updated_at",
  board_id: "board_id",
  "-board_id": "-board_id",
} as const;

export type GetTodosQueryParamsSortEnumKey =
  (typeof getTodosQueryParamsSortEnum)[keyof typeof getTodosQueryParamsSortEnum];

export const getTodosQueryParamsIncludeEnum = {
  board: "board",
} as const;

export type GetTodosQueryParamsIncludeEnumKey =
  (typeof getTodosQueryParamsIncludeEnum)[keyof typeof getTodosQueryParamsIncludeEnum];

export const fieldsBoardEnum4 = {
  id: "id",
  visibility: "visibility",
  created_at: "created_at",
  updated_at: "updated_at",
  owner_id: "owner_id",
  owner: "owner",
  todos: "todos",
} as const;

export type FieldsBoardEnum4Key = (typeof fieldsBoardEnum4)[keyof typeof fieldsBoardEnum4];

export const fieldsTodoEnum4 = {
  id: "id",
  title: "title",
  content: "content",
  status: "status",
  priority: "priority",
  created_at: "created_at",
  updated_at: "updated_at",
  board_id: "board_id",
  board: "board",
} as const;

export type FieldsTodoEnum4Key = (typeof fieldsTodoEnum4)[keyof typeof fieldsTodoEnum4];

export const fieldsUserEnum4 = {
  id: "id",
  email: "email",
  name: "name",
  board: "board",
  identities: "identities",
} as const;

export type FieldsUserEnum4Key = (typeof fieldsUserEnum4)[keyof typeof fieldsUserEnum4];

export type GetTodosQueryParams = {
  /**
   * @description Filters the query to results matching the given filter object
   * @type deepObject | undefined
   */
  filter?: TodoFilter;
  /**
   * @description Sort order to apply to the results
   * @type array | undefined
   */
  sort?: GetTodosQueryParamsSortEnumKey[];
  /**
   * @description Paginates the response with the limit and offset or keyset pagination.
   * @type object | undefined
   */
  page?: {
    /**
     * @type string | undefined
     */
    after?: string;
    /**
     * @type string | undefined
     */
    before?: string;
    /**
     * @default false
     * @type boolean | undefined
     */
    count?: boolean;
    /**
     * @minLength 1
     * @type integer | undefined
     */
    limit?: number;
    /**
     * @minLength 0
     * @type integer | undefined
     */
    offset?: number;
  };
  /**
   * @description Relationship paths to include in the response
   * @type array | undefined
   */
  include?: GetTodosQueryParamsIncludeEnumKey[];
  /**
   * @description Limits the response fields to only those listed for each type
   * @type object | undefined
   */
  fields?: {
    /**
     * @description Field names for board
     * @type array | undefined
     */
    board?: FieldsBoardEnum4Key[];
    /**
     * @description Field names for todo
     * @type array | undefined
     */
    todo?: FieldsTodoEnum4Key[];
    /**
     * @description Field names for user
     * @type array | undefined
     */
    user?: FieldsUserEnum4Key[];
  };
};

export const metaStatusesEnum = {
  blocked: "blocked",
  backlog: "backlog",
  in_progress: "in_progress",
  review: "review",
  done: "done",
  rejected: "rejected",
} as const;

export type MetaStatusesEnumKey = (typeof metaStatusesEnum)[keyof typeof metaStatusesEnum];

/**
 * @description Success
 */
export type GetTodos200 = {
  /**
   * @description An array of resource objects representing a todo
   * @type array | undefined
   */
  data?: Todo[];
  /**
   * @type array | undefined
   */
  included?: Board[];
  /**
   * @type object | undefined
   */
  meta?: {
    /**
     * @type array | undefined
     */
    statuses?: MetaStatusesEnumKey[];
    [key: string]: unknown;
  };
};

/**
 * @description General Error
 */
export type GetTodosError = Errors;

export type GetTodosQueryResponse = GetTodos200;

export type GetTodosQuery = {
  Response: GetTodos200;
  QueryParams: GetTodosQueryParams;
  Errors: any;
};
