/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Board } from "./Board";
import type { Errors } from "./Errors";
import type { Todo } from "./Todo";

export type GetTodosIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

export const getTodosIdQueryParamsIncludeEnum = {
  board: "board",
} as const;

export type GetTodosIdQueryParamsIncludeEnumKey =
  (typeof getTodosIdQueryParamsIncludeEnum)[keyof typeof getTodosIdQueryParamsIncludeEnum];

export const fieldsBoardEnum7 = {
  id: "id",
  visibility: "visibility",
  created_at: "created_at",
  updated_at: "updated_at",
  owner_id: "owner_id",
  owner: "owner",
  todos: "todos",
} as const;

export type FieldsBoardEnum7Key =
  (typeof fieldsBoardEnum7)[keyof typeof fieldsBoardEnum7];

export const fieldsTodoEnum7 = {
  id: "id",
  title: "title",
  content: "content",
  status: "status",
  priority: "priority",
  created_at: "created_at",
  updated_at: "updated_at",
  board_id: "board_id",
  board: "board",
} as const;

export type FieldsTodoEnum7Key =
  (typeof fieldsTodoEnum7)[keyof typeof fieldsTodoEnum7];

export const fieldsUserEnum7 = {
  id: "id",
  email: "email",
  name: "name",
  board: "board",
  identities: "identities",
} as const;

export type FieldsUserEnum7Key =
  (typeof fieldsUserEnum7)[keyof typeof fieldsUserEnum7];

export type GetTodosIdQueryParams = {
  /**
   * @description Relationship paths to include in the response
   * @type array | undefined
   */
  include?: GetTodosIdQueryParamsIncludeEnumKey[];
  /**
   * @description Limits the response fields to only those listed for each type
   * @type object | undefined
   */
  fields?: {
    /**
     * @description Field names for board
     * @type array | undefined
     */
    board?: FieldsBoardEnum7Key[];
    /**
     * @description Field names for todo
     * @type array | undefined
     */
    todo?: FieldsTodoEnum7Key[];
    /**
     * @description Field names for user
     * @type array | undefined
     */
    user?: FieldsUserEnum7Key[];
  };
};

/**
 * @description Success
 */
export type GetTodosId200 = {
  /**
   * @description A \"Resource object\" representing a todo
   * @type object | undefined
   */
  data?: Todo;
  /**
   * @type array | undefined
   */
  included?: Board[];
  /**
   * @type object | undefined
   */
  meta?: {
    [key: string]: any;
  };
};

/**
 * @description General Error
 */
export type GetTodosIdError = Errors;

export type GetTodosIdQueryResponse = GetTodosId200;

export type GetTodosIdQuery = {
  Response: GetTodosId200;
  PathParams: GetTodosIdPathParams;
  QueryParams: GetTodosIdQueryParams;
  Errors: any;
};
