/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Board } from "./Board";
import type { Errors } from "./Errors";
import type { User } from "./User";

export type PatchBoardsIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

export type PatchBoardsIdQueryParams = {
  /**
   * @description Relationship paths to include in the response
   * @pattern ^(owner)(,(owner))*$
   * @type string | undefined
   */
  include?: string;
  /**
   * @description Limits the response fields to only those listed for each type
   * @type object | undefined
   */
  fields?: {
    /**
     * @description Comma separated field names for board
     * @type string | undefined
     */
    board?: string;
    [key: string]: unknown;
  };
};

/**
 * @description Success
 */
export type PatchBoardsId200 = {
  /**
   * @description A \"Resource object\" representing a board
   * @type object | undefined
   */
  data?: Board;
  /**
   * @type array | undefined
   */
  included?: User[];
  /**
   * @type object | undefined
   */
  meta?: {
    [key: string]: any;
  };
};

/**
 * @description General Error
 */
export type PatchBoardsIdError = Errors;

export const attributesVisibilityEnum2 = {
  private: "private",
  public: "public",
} as const;

export type AttributesVisibilityEnum2Key =
  (typeof attributesVisibilityEnum2)[keyof typeof attributesVisibilityEnum2];

export const dataTypeEnum = {
  board: "board",
} as const;

export type DataTypeEnumKey = (typeof dataTypeEnum)[keyof typeof dataTypeEnum];

/**
 * @description Request body for the /boards/:id operation on board resource
 */
export type PatchBoardsIdMutationRequest = {
  /**
   * @type object
   */
  data: {
    /**
     * @type object | undefined
     */
    attributes?: {
      visibility?: AttributesVisibilityEnum2Key | null;
    };
    /**
     * @type string
     */
    id: string;
    /**
     * @type object | undefined
     */
    relationships?: object;
    type?: DataTypeEnumKey;
  };
};

export type PatchBoardsIdMutationResponse = PatchBoardsId200;

export type PatchBoardsIdMutation = {
  Response: PatchBoardsId200;
  Request: PatchBoardsIdMutationRequest;
  PathParams: PatchBoardsIdPathParams;
  QueryParams: PatchBoardsIdQueryParams;
  Errors: any;
};
