/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Board } from "./Board";
import type { Errors } from "./Errors";
import type { Todo } from "./Todo";

export type PatchTodosIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

export const patchTodosIdQueryParamsIncludeEnum = {
  board: "board",
} as const;

export type PatchTodosIdQueryParamsIncludeEnumKey =
  (typeof patchTodosIdQueryParamsIncludeEnum)[keyof typeof patchTodosIdQueryParamsIncludeEnum];

export const fieldsBoardEnum8 = {
  id: "id",
  visibility: "visibility",
  created_at: "created_at",
  updated_at: "updated_at",
  owner_id: "owner_id",
  owner: "owner",
  todos: "todos",
} as const;

export type FieldsBoardEnum8Key =
  (typeof fieldsBoardEnum8)[keyof typeof fieldsBoardEnum8];

export const fieldsTodoEnum8 = {
  id: "id",
  title: "title",
  content: "content",
  status: "status",
  priority: "priority",
  created_at: "created_at",
  updated_at: "updated_at",
  board_id: "board_id",
  board: "board",
} as const;

export type FieldsTodoEnum8Key =
  (typeof fieldsTodoEnum8)[keyof typeof fieldsTodoEnum8];

export const fieldsUserEnum8 = {
  id: "id",
  email: "email",
  name: "name",
  board: "board",
  identities: "identities",
} as const;

export type FieldsUserEnum8Key =
  (typeof fieldsUserEnum8)[keyof typeof fieldsUserEnum8];

export type PatchTodosIdQueryParams = {
  /**
   * @description Relationship paths to include in the response
   * @type array | undefined
   */
  include?: PatchTodosIdQueryParamsIncludeEnumKey[];
  /**
   * @description Limits the response fields to only those listed for each type
   * @type object | undefined
   */
  fields?: {
    /**
     * @description Field names for board
     * @type array | undefined
     */
    board?: FieldsBoardEnum8Key[];
    /**
     * @description Field names for todo
     * @type array | undefined
     */
    todo?: FieldsTodoEnum8Key[];
    /**
     * @description Field names for user
     * @type array | undefined
     */
    user?: FieldsUserEnum8Key[];
  };
};

/**
 * @description Success
 */
export type PatchTodosId200 = {
  /**
   * @description A \"Resource object\" representing a todo
   * @type object | undefined
   */
  data?: Todo;
  /**
   * @type array | undefined
   */
  included?: Board[];
  /**
   * @type object | undefined
   */
  meta?: {
    [key: string]: any;
  };
};

/**
 * @description General Error
 */
export type PatchTodosIdError = Errors;

export const attributesPriorityEnum3 = {
  low: "low",
  medium: "medium",
  high: "high",
  urgent: "urgent",
} as const;

export type AttributesPriorityEnum3Key =
  (typeof attributesPriorityEnum3)[keyof typeof attributesPriorityEnum3];

export const attributesStatusEnum3 = {
  blocked: "blocked",
  backlog: "backlog",
  in_progress: "in_progress",
  review: "review",
  done: "done",
  rejected: "rejected",
} as const;

export type AttributesStatusEnum3Key =
  (typeof attributesStatusEnum3)[keyof typeof attributesStatusEnum3];

export const dataTypeEnum3 = {
  todo: "todo",
} as const;

export type DataTypeEnum3Key =
  (typeof dataTypeEnum3)[keyof typeof dataTypeEnum3];

/**
 * @description Request body for the /todos/:id operation on todo resource
 */
export type PatchTodosIdMutationRequest = {
  /**
   * @type object
   */
  data: {
    /**
     * @type object | undefined
     */
    attributes?: {
      content?: string | null;
      priority?: AttributesPriorityEnum3Key | null;
      status?: AttributesStatusEnum3Key | null;
      title?: string | null;
    };
    /**
     * @type string
     */
    id: string;
    /**
     * @type object | undefined
     */
    relationships?: object;
    type?: DataTypeEnum3Key;
  };
};

export type PatchTodosIdMutationResponse = PatchTodosId200;

export type PatchTodosIdMutation = {
  Response: PatchTodosId200;
  Request: PatchTodosIdMutationRequest;
  PathParams: PatchTodosIdPathParams;
  QueryParams: PatchTodosIdQueryParams;
  Errors: any;
};
