/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Board } from "./Board";
import type { Errors } from "./Errors";
import type { User } from "./User";

export type PatchBoardsIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

export const patchBoardsIdQueryParamsIncludeEnum = {
  owner: "owner",
} as const;

export type PatchBoardsIdQueryParamsIncludeEnumKey =
  (typeof patchBoardsIdQueryParamsIncludeEnum)[keyof typeof patchBoardsIdQueryParamsIncludeEnum];

export const fieldsBoardEnum3 = {
  id: "id",
  visibility: "visibility",
  created_at: "created_at",
  updated_at: "updated_at",
  owner_id: "owner_id",
  owner: "owner",
  todos: "todos",
} as const;

export type FieldsBoardEnum3Key = (typeof fieldsBoardEnum3)[keyof typeof fieldsBoardEnum3];

export const fieldsTodoEnum3 = {
  id: "id",
  title: "title",
  content: "content",
  status: "status",
  priority: "priority",
  created_at: "created_at",
  updated_at: "updated_at",
  board_id: "board_id",
  board: "board",
} as const;

export type FieldsTodoEnum3Key = (typeof fieldsTodoEnum3)[keyof typeof fieldsTodoEnum3];

export const fieldsUserEnum3 = {
  id: "id",
  email: "email",
  name: "name",
  board: "board",
  identities: "identities",
} as const;

export type FieldsUserEnum3Key = (typeof fieldsUserEnum3)[keyof typeof fieldsUserEnum3];

export type PatchBoardsIdQueryParams = {
  /**
   * @description Relationship paths to include in the response
   * @type array | undefined
   */
  include?: PatchBoardsIdQueryParamsIncludeEnumKey[];
  /**
   * @description Limits the response fields to only those listed for each type
   * @type object | undefined
   */
  fields?: {
    /**
     * @description Field names for board
     * @type array | undefined
     */
    board?: FieldsBoardEnum3Key[];
    /**
     * @description Field names for todo
     * @type array | undefined
     */
    todo?: FieldsTodoEnum3Key[];
    /**
     * @description Field names for user
     * @type array | undefined
     */
    user?: FieldsUserEnum3Key[];
  };
};

/**
 * @description Success
 */
export type PatchBoardsId200 = {
  /**
   * @description A \"Resource object\" representing a board
   * @type object | undefined
   */
  data?: Board;
  /**
   * @type array | undefined
   */
  included?: User[];
  /**
   * @type object | undefined
   */
  meta?: {
    [key: string]: any;
  };
};

/**
 * @description General Error
 */
export type PatchBoardsIdError = Errors;

export const attributesVisibilityEnum2 = {
  private: "private",
  public: "public",
} as const;

export type AttributesVisibilityEnum2Key =
  (typeof attributesVisibilityEnum2)[keyof typeof attributesVisibilityEnum2];

export const dataTypeEnum = {
  board: "board",
} as const;

export type DataTypeEnumKey = (typeof dataTypeEnum)[keyof typeof dataTypeEnum];

/**
 * @description Request body for the /boards/:id operation on board resource
 */
export type PatchBoardsIdMutationRequest = {
  /**
   * @type object
   */
  data: {
    /**
     * @type object | undefined
     */
    attributes?: {
      visibility?: AttributesVisibilityEnum2Key | null;
    };
    /**
     * @type string
     */
    id: string;
    /**
     * @type object | undefined
     */
    relationships?: object;
    type?: DataTypeEnumKey;
  };
};

export type PatchBoardsIdMutationResponse = PatchBoardsId200;

export type PatchBoardsIdMutation = {
  Response: PatchBoardsId200;
  Request: PatchBoardsIdMutationRequest;
  PathParams: PatchBoardsIdPathParams;
  QueryParams: PatchBoardsIdQueryParams;
  Errors: any;
};
