/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Board } from "./Board";
import type { Errors } from "./Errors";
import type { Todo } from "./Todo";

export type PostTodosQueryParams = {
  /**
   * @description Relationship paths to include in the response
   * @pattern ^(board)(,(board))*$
   * @type string | undefined
   */
  include?: string;
  /**
   * @description Limits the response fields to only those listed for each type
   * @type object | undefined
   */
  fields?: {
    /**
     * @description Comma separated field names for todo
     * @type string | undefined
     */
    todo?: string;
    [key: string]: unknown;
  };
};

/**
 * @description Success
 */
export type PostTodos201 = {
  /**
   * @description A \"Resource object\" representing a todo
   * @type object | undefined
   */
  data?: Todo;
  /**
   * @type array | undefined
   */
  included?: Board[];
  /**
   * @type object | undefined
   */
  meta?: {
    [key: string]: any;
  };
};

/**
 * @description General Error
 */
export type PostTodosError = Errors;

export const attributesPriorityEnum2 = {
  low: "low",
  medium: "medium",
  high: "high",
  urgent: "urgent",
} as const;

export type AttributesPriorityEnum2Key =
  (typeof attributesPriorityEnum2)[keyof typeof attributesPriorityEnum2];

export const attributesStatusEnum2 = {
  blocked: "blocked",
  backlog: "backlog",
  in_progress: "in_progress",
  review: "review",
  done: "done",
  rejected: "rejected",
} as const;

export type AttributesStatusEnum2Key =
  (typeof attributesStatusEnum2)[keyof typeof attributesStatusEnum2];

export const dataTypeEnum2 = {
  todo: "todo",
} as const;

export type DataTypeEnum2Key =
  (typeof dataTypeEnum2)[keyof typeof dataTypeEnum2];

/**
 * @description Request body for the /todos operation on todo resource
 */
export type PostTodosMutationRequest = {
  /**
   * @type object
   */
  data: {
    /**
     * @type object | undefined
     */
    attributes?: {
      /**
       * @type string, uuid
       */
      board_id: string;
      /**
       * @type string
       */
      content: string;
      priority?: AttributesPriorityEnum2Key | null;
      status?: AttributesStatusEnum2Key | null;
      /**
       * @type string
       */
      title: string;
    };
    /**
     * @type object | undefined
     */
    relationships?: object;
    type?: DataTypeEnum2Key;
  };
};

export type PostTodosMutationResponse = PostTodos201;

export type PostTodosMutation = {
  Response: PostTodos201;
  Request: PostTodosMutationRequest;
  QueryParams: PostTodosQueryParams;
  Errors: any;
};
