/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Board } from "./Board";
import type { Errors } from "./Errors";
import type { Todo } from "./Todo";

export const postTodosQueryParamsIncludeEnum = {
  board: "board",
} as const;

export type PostTodosQueryParamsIncludeEnumKey =
  (typeof postTodosQueryParamsIncludeEnum)[keyof typeof postTodosQueryParamsIncludeEnum];

export const fieldsBoardEnum5 = {
  id: "id",
  visibility: "visibility",
  created_at: "created_at",
  updated_at: "updated_at",
  owner_id: "owner_id",
  owner: "owner",
  todos: "todos",
} as const;

export type FieldsBoardEnum5Key =
  (typeof fieldsBoardEnum5)[keyof typeof fieldsBoardEnum5];

export const fieldsTodoEnum5 = {
  id: "id",
  title: "title",
  content: "content",
  status: "status",
  priority: "priority",
  created_at: "created_at",
  updated_at: "updated_at",
  board_id: "board_id",
  board: "board",
} as const;

export type FieldsTodoEnum5Key =
  (typeof fieldsTodoEnum5)[keyof typeof fieldsTodoEnum5];

export const fieldsUserEnum5 = {
  id: "id",
  email: "email",
  name: "name",
  board: "board",
  identities: "identities",
} as const;

export type FieldsUserEnum5Key =
  (typeof fieldsUserEnum5)[keyof typeof fieldsUserEnum5];

export type PostTodosQueryParams = {
  /**
   * @description Relationship paths to include in the response
   * @type array | undefined
   */
  include?: PostTodosQueryParamsIncludeEnumKey[];
  /**
   * @description Limits the response fields to only those listed for each type
   * @type object | undefined
   */
  fields?: {
    /**
     * @description Field names for board
     * @type array | undefined
     */
    board?: FieldsBoardEnum5Key[];
    /**
     * @description Field names for todo
     * @type array | undefined
     */
    todo?: FieldsTodoEnum5Key[];
    /**
     * @description Field names for user
     * @type array | undefined
     */
    user?: FieldsUserEnum5Key[];
  };
};

/**
 * @description Success
 */
export type PostTodos201 = {
  /**
   * @description A \"Resource object\" representing a todo
   * @type object | undefined
   */
  data?: Todo;
  /**
   * @type array | undefined
   */
  included?: Board[];
  /**
   * @type object | undefined
   */
  meta?: {
    [key: string]: any;
  };
};

/**
 * @description General Error
 */
export type PostTodosError = Errors;

export const attributesPriorityEnum2 = {
  low: "low",
  medium: "medium",
  high: "high",
  urgent: "urgent",
} as const;

export type AttributesPriorityEnum2Key =
  (typeof attributesPriorityEnum2)[keyof typeof attributesPriorityEnum2];

export const attributesStatusEnum2 = {
  blocked: "blocked",
  backlog: "backlog",
  in_progress: "in_progress",
  review: "review",
  done: "done",
  rejected: "rejected",
} as const;

export type AttributesStatusEnum2Key =
  (typeof attributesStatusEnum2)[keyof typeof attributesStatusEnum2];

export const dataTypeEnum2 = {
  todo: "todo",
} as const;

export type DataTypeEnum2Key =
  (typeof dataTypeEnum2)[keyof typeof dataTypeEnum2];

/**
 * @description Request body for the /todos operation on todo resource
 */
export type PostTodosMutationRequest = {
  /**
   * @type object
   */
  data: {
    /**
     * @type object | undefined
     */
    attributes?: {
      /**
       * @type string, uuid
       */
      board_id: string;
      /**
       * @type string
       */
      content: string;
      priority?: AttributesPriorityEnum2Key | null;
      status?: AttributesStatusEnum2Key | null;
      /**
       * @type string
       */
      title: string;
    };
    /**
     * @type object | undefined
     */
    relationships?: object;
    type?: DataTypeEnum2Key;
  };
};

export type PostTodosMutationResponse = PostTodos201;

export type PostTodosMutation = {
  Response: PostTodos201;
  Request: PostTodosMutationRequest;
  QueryParams: PostTodosQueryParams;
  Errors: any;
};
