/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const todoFilterPriorityEqEnum = {
  low: "low",
  medium: "medium",
  high: "high",
  urgent: "urgent",
} as const;

export type TodoFilterPriorityEqEnumKey =
  (typeof todoFilterPriorityEqEnum)[keyof typeof todoFilterPriorityEqEnum];

export const todoFilterPriorityGreaterThanEnum = {
  low: "low",
  medium: "medium",
  high: "high",
  urgent: "urgent",
} as const;

export type TodoFilterPriorityGreaterThanEnumKey =
  (typeof todoFilterPriorityGreaterThanEnum)[keyof typeof todoFilterPriorityGreaterThanEnum];

export const todoFilterPriorityGreaterThanOrEqualEnum = {
  low: "low",
  medium: "medium",
  high: "high",
  urgent: "urgent",
} as const;

export type TodoFilterPriorityGreaterThanOrEqualEnumKey =
  (typeof todoFilterPriorityGreaterThanOrEqualEnum)[keyof typeof todoFilterPriorityGreaterThanOrEqualEnum];

export const todoFilterPriorityInEnum = {
  low: "low",
  medium: "medium",
  high: "high",
  urgent: "urgent",
} as const;

export type TodoFilterPriorityInEnumKey =
  (typeof todoFilterPriorityInEnum)[keyof typeof todoFilterPriorityInEnum];

export const todoFilterPriorityLessThanEnum = {
  low: "low",
  medium: "medium",
  high: "high",
  urgent: "urgent",
} as const;

export type TodoFilterPriorityLessThanEnumKey =
  (typeof todoFilterPriorityLessThanEnum)[keyof typeof todoFilterPriorityLessThanEnum];

export const todoFilterPriorityLessThanOrEqualEnum = {
  low: "low",
  medium: "medium",
  high: "high",
  urgent: "urgent",
} as const;

export type TodoFilterPriorityLessThanOrEqualEnumKey =
  (typeof todoFilterPriorityLessThanOrEqualEnum)[keyof typeof todoFilterPriorityLessThanOrEqualEnum];

export const todoFilterPriorityNotEqEnum = {
  low: "low",
  medium: "medium",
  high: "high",
  urgent: "urgent",
} as const;

export type TodoFilterPriorityNotEqEnumKey =
  (typeof todoFilterPriorityNotEqEnum)[keyof typeof todoFilterPriorityNotEqEnum];

export type TodoFilterPriority = {
  /**
   * @type string | undefined
   */
  eq?: TodoFilterPriorityEqEnumKey;
  /**
   * @type string | undefined
   */
  greater_than?: TodoFilterPriorityGreaterThanEnumKey;
  /**
   * @type string | undefined
   */
  greater_than_or_equal?: TodoFilterPriorityGreaterThanOrEqualEnumKey;
  /**
   * @type array | undefined
   */
  in?: TodoFilterPriorityInEnumKey[];
  /**
   * @type string | undefined
   */
  is_distinct_from?: string;
  /**
   * @type boolean | undefined
   */
  is_nil?: boolean;
  /**
   * @type string | undefined
   */
  is_not_distinct_from?: string;
  /**
   * @type string | undefined
   */
  less_than?: TodoFilterPriorityLessThanEnumKey;
  /**
   * @type string | undefined
   */
  less_than_or_equal?: TodoFilterPriorityLessThanOrEqualEnumKey;
  /**
   * @type string | undefined
   */
  not_eq?: TodoFilterPriorityNotEqEnumKey;
};
