/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type TodoFilterCreatedAt = {
  eq?: any;
  greater_than?: any;
  greater_than_or_equal?: any;
  /**
   * @type array | undefined
   */
  in?: any[];
  /**
   * @type string | undefined
   */
  is_distinct_from?: string;
  /**
   * @type boolean | undefined
   */
  is_nil?: boolean;
  /**
   * @type string | undefined
   */
  is_not_distinct_from?: string;
  less_than?: any;
  less_than_or_equal?: any;
  not_eq?: any;
};
