/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const todoFilterStatusEqEnum = {
    "blocked": "blocked",
    "backlog": "backlog",
    "in_progress": "in_progress",
    "review": "review",
    "done": "done",
    "rejected": "rejected"
} as const;

export type TodoFilterStatusEqEnum = (typeof todoFilterStatusEqEnum)[keyof typeof todoFilterStatusEqEnum];

export const todoFilterStatusGreaterThanEnum = {
    "blocked": "blocked",
    "backlog": "backlog",
    "in_progress": "in_progress",
    "review": "review",
    "done": "done",
    "rejected": "rejected"
} as const;

export type TodoFilterStatusGreaterThanEnum = (typeof todoFilterStatusGreaterThanEnum)[keyof typeof todoFilterStatusGreaterThanEnum];

export const todoFilterStatusGreaterThanOrEqualEnum = {
    "blocked": "blocked",
    "backlog": "backlog",
    "in_progress": "in_progress",
    "review": "review",
    "done": "done",
    "rejected": "rejected"
} as const;

export type TodoFilterStatusGreaterThanOrEqualEnum = (typeof todoFilterStatusGreaterThanOrEqualEnum)[keyof typeof todoFilterStatusGreaterThanOrEqualEnum];

export const todoFilterStatusInEnum = {
    "blocked": "blocked",
    "backlog": "backlog",
    "in_progress": "in_progress",
    "review": "review",
    "done": "done",
    "rejected": "rejected"
} as const;

export type TodoFilterStatusInEnum = (typeof todoFilterStatusInEnum)[keyof typeof todoFilterStatusInEnum];

export const todoFilterStatusLessThanEnum = {
    "blocked": "blocked",
    "backlog": "backlog",
    "in_progress": "in_progress",
    "review": "review",
    "done": "done",
    "rejected": "rejected"
} as const;

export type TodoFilterStatusLessThanEnum = (typeof todoFilterStatusLessThanEnum)[keyof typeof todoFilterStatusLessThanEnum];

export const todoFilterStatusLessThanOrEqualEnum = {
    "blocked": "blocked",
    "backlog": "backlog",
    "in_progress": "in_progress",
    "review": "review",
    "done": "done",
    "rejected": "rejected"
} as const;

export type TodoFilterStatusLessThanOrEqualEnum = (typeof todoFilterStatusLessThanOrEqualEnum)[keyof typeof todoFilterStatusLessThanOrEqualEnum];

export const todoFilterStatusNotEqEnum = {
    "blocked": "blocked",
    "backlog": "backlog",
    "in_progress": "in_progress",
    "review": "review",
    "done": "done",
    "rejected": "rejected"
} as const;

export type TodoFilterStatusNotEqEnum = (typeof todoFilterStatusNotEqEnum)[keyof typeof todoFilterStatusNotEqEnum];

export type TodoFilterStatus = {
    /**
     * @type string | undefined
    */
    eq?: TodoFilterStatusEqEnum;
    /**
     * @type string | undefined
    */
    greater_than?: TodoFilterStatusGreaterThanEnum;
    /**
     * @type string | undefined
    */
    greater_than_or_equal?: TodoFilterStatusGreaterThanOrEqualEnum;
    /**
     * @type array | undefined
    */
    in?: TodoFilterStatusInEnum[];
    /**
     * @type string | undefined
    */
    is_distinct_from?: string;
    /**
     * @type boolean | undefined
    */
    is_nil?: boolean;
    /**
     * @type string | undefined
    */
    is_not_distinct_from?: string;
    /**
     * @type string | undefined
    */
    less_than?: TodoFilterStatusLessThanEnum;
    /**
     * @type string | undefined
    */
    less_than_or_equal?: TodoFilterStatusLessThanOrEqualEnum;
    /**
     * @type string | undefined
    */
    not_eq?: TodoFilterStatusNotEqEnum;
};