/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const attributesPriorityEnum = {
  low: "low",
  medium: "medium",
  high: "high",
  urgent: "urgent",
} as const;

export type AttributesPriorityEnumKey =
  (typeof attributesPriorityEnum)[keyof typeof attributesPriorityEnum];

export const attributesStatusEnum = {
  blocked: "blocked",
  backlog: "backlog",
  in_progress: "in_progress",
  review: "review",
  done: "done",
  rejected: "rejected",
} as const;

export type AttributesStatusEnumKey =
  (typeof attributesStatusEnum)[keyof typeof attributesStatusEnum];

/**
 * @description A \"Resource object\" representing a todo
 */
export type Todo = {
  /**
   * @description An attributes object for a todo
   * @type object | undefined
   */
  attributes?: {
    /**
     * @description Field included by default.
     * @type string, uuid
     */
    board_id: string;
    /**
     * @description Field included by default.
     * @type string
     */
    content: string;
    /**
     * @description Field included by default.
     */
    created_at: any;
    /**
     * @description Field included by default.
     * @type string
     */
    priority: AttributesPriorityEnumKey;
    /**
     * @description Field included by default.
     * @type string
     */
    status: AttributesStatusEnumKey;
    /**
     * @description Field included by default.
     * @type string
     */
    title: string;
    /**
     * @description Field included by default.
     */
    updated_at: any;
  };
  /**
   * @type string
   */
  id: string;
  /**
   * @description A relationships object for a todo
   * @type object | undefined
   */
  relationships?: {
    board?: {
      /**
       * @description An identifier for board
       * @type object
       */
      data?: {
        /**
         * @type string
         */
        id: string;
        /**
         * @type object | undefined
         */
        meta?: {
          [key: string]: any;
        };
        /**
         * @type string
         */
        type: string;
      } | null;
    };
  };
  /**
   * @type string
   */
  type: string;
};
