/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BoardFilter } from "./BoardFilter";
import type { TodoFilterBoardId } from "./TodoFilterBoardId";
import type { TodoFilterContent } from "./TodoFilterContent";
import type { TodoFilterCreatedAt } from "./TodoFilterCreatedAt";
import type { TodoFilterId } from "./TodoFilterId";
import type { TodoFilterPriority } from "./TodoFilterPriority";
import type { TodoFilterStatus } from "./TodoFilterStatus";
import type { TodoFilterTitle } from "./TodoFilterTitle";
import type { TodoFilterUpdatedAt } from "./TodoFilterUpdatedAt";

/**
 * @description Filters the query to results matching the given filter object
 */
export type TodoFilter = {
  /**
   * @type array | undefined
   */
  and?: TodoFilter[];
  /**
   * @description Filters the query to results matching the given filter object
   * @type deepObject | undefined
   */
  board?: BoardFilter;
  /**
   * @type object | undefined
   */
  board_id?: TodoFilterBoardId;
  /**
   * @type object | undefined
   */
  content?: TodoFilterContent;
  /**
   * @type object | undefined
   */
  created_at?: TodoFilterCreatedAt;
  /**
   * @type object | undefined
   */
  id?: TodoFilterId;
  /**
   * @description Filters the query to results matching the given filter object
   * @type deepObject | undefined
   */
  not?: TodoFilter;
  /**
   * @type array | undefined
   */
  or?: TodoFilter[];
  /**
   * @type object | undefined
   */
  priority?: TodoFilterPriority;
  /**
   * @type object | undefined
   */
  status?: TodoFilterStatus;
  /**
   * @type object | undefined
   */
  title?: TodoFilterTitle;
  /**
   * @type object | undefined
   */
  updated_at?: TodoFilterUpdatedAt;
};
