/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type TodoFilterContent = {
  /**
   * @type string | undefined
   */
  contains?: string;
  /**
   * @type string | undefined
   */
  eq?: string;
  /**
   * @type string | undefined
   */
  greater_than?: string;
  /**
   * @type string | undefined
   */
  greater_than_or_equal?: string;
  /**
   * @type string | undefined
   */
  ilike?: string;
  /**
   * @type array | undefined
   */
  in?: string[];
  /**
   * @type string | undefined
   */
  is_distinct_from?: string;
  /**
   * @type boolean | undefined
   */
  is_nil?: boolean;
  /**
   * @type string | undefined
   */
  is_not_distinct_from?: string;
  /**
   * @type string | undefined
   */
  less_than?: string;
  /**
   * @type string | undefined
   */
  less_than_or_equal?: string;
  /**
   * @type string | undefined
   */
  like?: string;
  /**
   * @type string | undefined
   */
  not_eq?: string;
};
