/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const todoFilterStatusEqEnum = {
  blocked: "blocked",
  backlog: "backlog",
  in_progress: "in_progress",
  review: "review",
  done: "done",
  rejected: "rejected",
} as const;

export type TodoFilterStatusEqEnumKey =
  (typeof todoFilterStatusEqEnum)[keyof typeof todoFilterStatusEqEnum];

export const todoFilterStatusGreaterThanEnum = {
  blocked: "blocked",
  backlog: "backlog",
  in_progress: "in_progress",
  review: "review",
  done: "done",
  rejected: "rejected",
} as const;

export type TodoFilterStatusGreaterThanEnumKey =
  (typeof todoFilterStatusGreaterThanEnum)[keyof typeof todoFilterStatusGreaterThanEnum];

export const todoFilterStatusGreaterThanOrEqualEnum = {
  blocked: "blocked",
  backlog: "backlog",
  in_progress: "in_progress",
  review: "review",
  done: "done",
  rejected: "rejected",
} as const;

export type TodoFilterStatusGreaterThanOrEqualEnumKey =
  (typeof todoFilterStatusGreaterThanOrEqualEnum)[keyof typeof todoFilterStatusGreaterThanOrEqualEnum];

export const todoFilterStatusInEnum = {
  blocked: "blocked",
  backlog: "backlog",
  in_progress: "in_progress",
  review: "review",
  done: "done",
  rejected: "rejected",
} as const;

export type TodoFilterStatusInEnumKey =
  (typeof todoFilterStatusInEnum)[keyof typeof todoFilterStatusInEnum];

export const todoFilterStatusLessThanEnum = {
  blocked: "blocked",
  backlog: "backlog",
  in_progress: "in_progress",
  review: "review",
  done: "done",
  rejected: "rejected",
} as const;

export type TodoFilterStatusLessThanEnumKey =
  (typeof todoFilterStatusLessThanEnum)[keyof typeof todoFilterStatusLessThanEnum];

export const todoFilterStatusLessThanOrEqualEnum = {
  blocked: "blocked",
  backlog: "backlog",
  in_progress: "in_progress",
  review: "review",
  done: "done",
  rejected: "rejected",
} as const;

export type TodoFilterStatusLessThanOrEqualEnumKey =
  (typeof todoFilterStatusLessThanOrEqualEnum)[keyof typeof todoFilterStatusLessThanOrEqualEnum];

export const todoFilterStatusNotEqEnum = {
  blocked: "blocked",
  backlog: "backlog",
  in_progress: "in_progress",
  review: "review",
  done: "done",
  rejected: "rejected",
} as const;

export type TodoFilterStatusNotEqEnumKey =
  (typeof todoFilterStatusNotEqEnum)[keyof typeof todoFilterStatusNotEqEnum];

export type TodoFilterStatus = {
  /**
   * @type string | undefined
   */
  eq?: TodoFilterStatusEqEnumKey;
  /**
   * @type string | undefined
   */
  greater_than?: TodoFilterStatusGreaterThanEnumKey;
  /**
   * @type string | undefined
   */
  greater_than_or_equal?: TodoFilterStatusGreaterThanOrEqualEnumKey;
  /**
   * @type array | undefined
   */
  in?: TodoFilterStatusInEnumKey[];
  /**
   * @type string | undefined
   */
  is_distinct_from?: string;
  /**
   * @type boolean | undefined
   */
  is_nil?: boolean;
  /**
   * @type string | undefined
   */
  is_not_distinct_from?: string;
  /**
   * @type string | undefined
   */
  less_than?: TodoFilterStatusLessThanEnumKey;
  /**
   * @type string | undefined
   */
  less_than_or_equal?: TodoFilterStatusLessThanOrEqualEnumKey;
  /**
   * @type string | undefined
   */
  not_eq?: TodoFilterStatusNotEqEnumKey;
};
