/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const todoFilterPriorityEqEnum = {
    "low": "low",
    "medium": "medium",
    "high": "high",
    "urgent": "urgent"
} as const;

export type TodoFilterPriorityEqEnum = (typeof todoFilterPriorityEqEnum)[keyof typeof todoFilterPriorityEqEnum];

export const todoFilterPriorityGreaterThanEnum = {
    "low": "low",
    "medium": "medium",
    "high": "high",
    "urgent": "urgent"
} as const;

export type TodoFilterPriorityGreaterThanEnum = (typeof todoFilterPriorityGreaterThanEnum)[keyof typeof todoFilterPriorityGreaterThanEnum];

export const todoFilterPriorityGreaterThanOrEqualEnum = {
    "low": "low",
    "medium": "medium",
    "high": "high",
    "urgent": "urgent"
} as const;

export type TodoFilterPriorityGreaterThanOrEqualEnum = (typeof todoFilterPriorityGreaterThanOrEqualEnum)[keyof typeof todoFilterPriorityGreaterThanOrEqualEnum];

export const todoFilterPriorityInEnum = {
    "low": "low",
    "medium": "medium",
    "high": "high",
    "urgent": "urgent"
} as const;

export type TodoFilterPriorityInEnum = (typeof todoFilterPriorityInEnum)[keyof typeof todoFilterPriorityInEnum];

export const todoFilterPriorityLessThanEnum = {
    "low": "low",
    "medium": "medium",
    "high": "high",
    "urgent": "urgent"
} as const;

export type TodoFilterPriorityLessThanEnum = (typeof todoFilterPriorityLessThanEnum)[keyof typeof todoFilterPriorityLessThanEnum];

export const todoFilterPriorityLessThanOrEqualEnum = {
    "low": "low",
    "medium": "medium",
    "high": "high",
    "urgent": "urgent"
} as const;

export type TodoFilterPriorityLessThanOrEqualEnum = (typeof todoFilterPriorityLessThanOrEqualEnum)[keyof typeof todoFilterPriorityLessThanOrEqualEnum];

export const todoFilterPriorityNotEqEnum = {
    "low": "low",
    "medium": "medium",
    "high": "high",
    "urgent": "urgent"
} as const;

export type TodoFilterPriorityNotEqEnum = (typeof todoFilterPriorityNotEqEnum)[keyof typeof todoFilterPriorityNotEqEnum];

export type TodoFilterPriority = {
    /**
     * @type string | undefined
    */
    eq?: TodoFilterPriorityEqEnum;
    /**
     * @type string | undefined
    */
    greater_than?: TodoFilterPriorityGreaterThanEnum;
    /**
     * @type string | undefined
    */
    greater_than_or_equal?: TodoFilterPriorityGreaterThanOrEqualEnum;
    /**
     * @type array | undefined
    */
    in?: TodoFilterPriorityInEnum[];
    /**
     * @type string | undefined
    */
    is_distinct_from?: string;
    /**
     * @type boolean | undefined
    */
    is_nil?: boolean;
    /**
     * @type string | undefined
    */
    is_not_distinct_from?: string;
    /**
     * @type string | undefined
    */
    less_than?: TodoFilterPriorityLessThanEnum;
    /**
     * @type string | undefined
    */
    less_than_or_equal?: TodoFilterPriorityLessThanOrEqualEnum;
    /**
     * @type string | undefined
    */
    not_eq?: TodoFilterPriorityNotEqEnum;
};