/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description A \"Resource object\" representing a user
 */
export type User = {
  /**
   * @description An attributes object for a user
   * @type object | undefined
   */
  attributes?: {
    /**
     * @description Field included by default.
     * @type string
     */
    email: string;
    /**
     * @description Field included by default.
     */
    name?: string | null;
  };
  /**
   * @type string
   */
  id: string;
  /**
   * @description A relationships object for a user
   * @type object | undefined
   */
  relationships?: {
    board?: {
      /**
       * @description An identifier for board
       * @type object
       */
      data?: {
        /**
         * @type string
         */
        id: string;
        /**
         * @type object | undefined
         */
        meta?: {
          [key: string]: any;
        };
        /**
         * @type string
         */
        type: string;
      } | null;
    };
  };
  /**
   * @type string
   */
  type: string;
};
