/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../../lib/client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "../../lib/client";
import type {
  GetBoardsQueryResponse,
  GetBoardsQueryParams,
} from "../models/GetBoards";

function getGetBoardsUrl() {
  const res = { method: "GET", url: `/boards` as const };
  return res;
}

/**
 * @description /boards operation on board resource
 * {@link /boards}
 */
export async function getBoards(
  params?: GetBoardsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetBoardsQueryResponse,
    ResponseErrorConfig,
    unknown
  >({
    method: "GET",
    url: getGetBoardsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
