/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../../lib/client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../lib/client";
import type {
  GetBoardsIdQueryResponse,
  GetBoardsIdPathParams,
  GetBoardsIdQueryParams,
} from "../models/GetBoardsId";

function getGetBoardsIdUrl(id: GetBoardsIdPathParams["id"]) {
  const res = { method: "GET", url: `/boards/${id}` as const };
  return res;
}

/**
 * @description /boards/:id operation on board resource
 * {@link /boards/:id}
 */
export async function getBoardsId(
  id: GetBoardsIdPathParams["id"],
  params?: GetBoardsIdQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<GetBoardsIdQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: "GET",
    url: getGetBoardsIdUrl(id).url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
