/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../../lib/client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../lib/client";
import type {
  PatchBoardsIdMutationRequest,
  PatchBoardsIdMutationResponse,
  PatchBoardsIdPathParams,
  PatchBoardsIdQueryParams,
} from "../models/PatchBoardsId";

function getPatchBoardsIdUrl(id: PatchBoardsIdPathParams["id"]) {
  const res = { method: "PATCH", url: `/boards/${id}` as const };
  return res;
}

/**
 * @description /boards/:id operation on board resource
 * {@link /boards/:id}
 */
export async function patchBoardsId(
  id: PatchBoardsIdPathParams["id"],
  data: PatchBoardsIdMutationRequest,
  params?: PatchBoardsIdQueryParams,
  config: Partial<RequestConfig<PatchBoardsIdMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchBoardsIdMutationResponse,
    ResponseErrorConfig<Error>,
    PatchBoardsIdMutationRequest
  >({
    method: "PATCH",
    url: getPatchBoardsIdUrl(id).url.toString(),
    params,
    data: requestData,
    ...requestConfig,
    headers: {
      "Content-Type": "application/vnd.api+json",
      ...requestConfig.headers,
    },
  });
  return res.data;
}
