defmodule AshFramework.Repo.Migrations.AddBoardsAndMoveTodosToBoards do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:boards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:boards) do
      add :visibility, :text, null: false, default: "private"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "boards_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:boards, [:owner_id], name: "boards_unique_owner_index")

    execute("""
    INSERT INTO boards (owner_id, visibility, created_at, updated_at)
    SELECT id, 'private', now() AT TIME ZONE 'utc', now() AT TIME ZONE 'utc'
    FROM users
    ON CONFLICT (owner_id) DO NOTHING
    """)

    drop constraint(:todos, "todos_user_id_fkey")

    rename table(:todos), :user_id, to: :board_id

    execute("""
    UPDATE todos
    SET board_id = boards.id
    FROM boards
    WHERE boards.owner_id = todos.board_id
    """)

    alter table(:todos) do
      modify :priority, :integer
      modify :status, :text, default: "backlog"

      modify :board_id,
             references(:boards,
               column: :id,
               name: "todos_board_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:todos, "todos_board_id_fkey")

    execute("""
    UPDATE todos
    SET board_id = boards.owner_id
    FROM boards
    WHERE boards.id = todos.board_id
    """)

    alter table(:todos) do
      modify :board_id,
             references(:users,
               column: :id,
               name: "todos_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    rename table(:todos), :board_id, to: :user_id

    drop_if_exists unique_index(:boards, [:owner_id], name: "boards_unique_owner_index")

    drop constraint(:boards, "boards_owner_id_fkey")

    alter table(:boards) do
      remove :owner_id
      remove :updated_at
      remove :created_at
      remove :visibility
    end

    drop table(:boards)

    execute("""
    ALTER TABLE todos
    DROP CONSTRAINT IF EXISTS todos_priority_check
    """)

    execute("""
    ALTER TABLE todos
    ALTER COLUMN priority DROP DEFAULT,
    ALTER COLUMN priority TYPE text
    USING (
      CASE priority
        WHEN 1 THEN 'low'
        WHEN 2 THEN 'medium'
        WHEN 3 THEN 'high'
        WHEN 4 THEN 'urgent'
      END
    ),
    ALTER COLUMN priority SET DEFAULT 'medium'
    """)

    alter table(:todos) do
      modify :status, :text, default: "todo"
    end

    execute("""
    ALTER TABLE todos
    ADD CONSTRAINT todos_priority_check
    CHECK (priority IN ('low', 'medium', 'high', 'urgent'))
    """)
  end
end
