/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import useSWRMutation from "swr/mutation";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../lib/client";
import type {
  DeleteTodosIdMutationResponse,
  DeleteTodosIdPathParams,
  DeleteTodosIdQueryParams,
} from "../../models/DeleteTodosId";
import type { SWRMutationConfiguration } from "swr/mutation";
import { deleteTodosId } from "../../clients/deleteTodosId";

export const deleteTodosIdMutationKey = () => [{ url: "/todos/:id" }] as const;

export type DeleteTodosIdMutationKey = ReturnType<typeof deleteTodosIdMutationKey>;

/**
 * @description /todos/:id operation on todo resource
 * {@link /todos/:id}
 */
export function useDeleteTodosId(
  id: DeleteTodosIdPathParams["id"],
  params?: DeleteTodosIdQueryParams,
  options: {
    mutation?: SWRMutationConfiguration<
      DeleteTodosIdMutationResponse,
      ResponseErrorConfig<Error>,
      DeleteTodosIdMutationKey | null,
      never
    > & { throwOnError?: boolean };
    client?: Partial<RequestConfig> & { client?: Client };
    shouldFetch?: boolean;
  } = {},
) {
  const { mutation: mutationOptions, client: config = {}, shouldFetch = true } = options ?? {};
  const mutationKey = deleteTodosIdMutationKey();

  return useSWRMutation<
    DeleteTodosIdMutationResponse,
    ResponseErrorConfig<Error>,
    DeleteTodosIdMutationKey | null
  >(
    shouldFetch ? mutationKey : null,
    async (_url) => {
      return deleteTodosId(id, params, config);
    },
    mutationOptions,
  );
}
