/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import useSWR from "swr";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../lib/client";
import type { GetBoardsQueryResponse, GetBoardsQueryParams } from "../../models/GetBoards";
import { getBoards } from "../../clients/getBoards";

export const getBoardsQueryKey = (params?: GetBoardsQueryParams) =>
  [{ url: "/boards" }, ...(params ? [params] : [])] as const;

export type GetBoardsQueryKey = ReturnType<typeof getBoardsQueryKey>;

export function getBoardsQueryOptions(
  params?: GetBoardsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  return {
    fetcher: async () => {
      return getBoards(params, config);
    },
  };
}

/**
 * @description /boards operation on board resource
 * {@link /boards}
 */
export function useGetBoards(
  params?: GetBoardsQueryParams,
  options: {
    query?: Parameters<typeof useSWR<GetBoardsQueryResponse, ResponseErrorConfig<Error>>>[2];
    client?: Partial<RequestConfig> & { client?: Client };
    shouldFetch?: boolean;
    immutable?: boolean;
  } = {},
) {
  const { query: queryOptions, client: config = {}, shouldFetch = true, immutable } = options ?? {};

  const queryKey = getBoardsQueryKey(params);

  return useSWR<GetBoardsQueryResponse, ResponseErrorConfig<Error>, GetBoardsQueryKey | null>(
    shouldFetch ? queryKey : null,
    {
      ...getBoardsQueryOptions(params, config),
      ...(immutable
        ? {
            revalidateIfStale: false,
            revalidateOnFocus: false,
            revalidateOnReconnect: false,
          }
        : {}),
      ...queryOptions,
    },
  );
}
