/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import useSWR from "swr";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "../../../lib/client";
import type {
  GetTodosQueryResponse,
  GetTodosQueryParams,
} from "../../models/GetTodos";
import { getTodos } from "../../clients/getTodos";

export const getTodosQueryKey = (params?: GetTodosQueryParams) =>
  [{ url: "/todos" }, ...(params ? [params] : [])] as const;

export type GetTodosQueryKey = ReturnType<typeof getTodosQueryKey>;

export function getTodosQueryOptions(
  params?: GetTodosQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  return {
    fetcher: async () => {
      return getTodos(params, config);
    },
  };
}

/**
 * @description /todos operation on todo resource
 * {@link /todos}
 */
export function useGetTodos(
  params?: GetTodosQueryParams,
  options: {
    query?: Parameters<
      typeof useSWR<GetTodosQueryResponse, ResponseErrorConfig<Error>>
    >[2];
    client?: Partial<RequestConfig> & { client?: Client };
    shouldFetch?: boolean;
    immutable?: boolean;
  } = {},
) {
  const {
    query: queryOptions,
    client: config = {},
    shouldFetch = true,
    immutable,
  } = options ?? {};

  const queryKey = getTodosQueryKey(params);

  return useSWR<
    GetTodosQueryResponse,
    ResponseErrorConfig<Error>,
    GetTodosQueryKey | null
  >(shouldFetch ? queryKey : null, {
    ...getTodosQueryOptions(params, config),
    ...(immutable
      ? {
          revalidateIfStale: false,
          revalidateOnFocus: false,
          revalidateOnReconnect: false,
        }
      : {}),
    ...queryOptions,
  });
}
