/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import useSWR from "swr";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "../../../lib/client";
import type {
  GetTodosIdQueryResponse,
  GetTodosIdPathParams,
  GetTodosIdQueryParams,
} from "../../models/GetTodosId";
import { getTodosId } from "../../clients/getTodosId";

export const getTodosIdQueryKey = (
  id: GetTodosIdPathParams["id"],
  params?: GetTodosIdQueryParams,
) =>
  [
    { url: "/todos/:id", params: { id: id } },
    ...(params ? [params] : []),
  ] as const;

export type GetTodosIdQueryKey = ReturnType<typeof getTodosIdQueryKey>;

export function getTodosIdQueryOptions(
  id: GetTodosIdPathParams["id"],
  params?: GetTodosIdQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  return {
    fetcher: async () => {
      return getTodosId(id, params, config);
    },
  };
}

/**
 * @description /todos/:id operation on todo resource
 * {@link /todos/:id}
 */
export function useGetTodosId(
  id: GetTodosIdPathParams["id"],
  params?: GetTodosIdQueryParams,
  options: {
    query?: Parameters<
      typeof useSWR<GetTodosIdQueryResponse, ResponseErrorConfig<Error>>
    >[2];
    client?: Partial<RequestConfig> & { client?: Client };
    shouldFetch?: boolean;
    immutable?: boolean;
  } = {},
) {
  const {
    query: queryOptions,
    client: config = {},
    shouldFetch = true,
    immutable,
  } = options ?? {};

  const queryKey = getTodosIdQueryKey(id, params);

  return useSWR<
    GetTodosIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetTodosIdQueryKey | null
  >(shouldFetch ? queryKey : null, {
    ...getTodosIdQueryOptions(id, params, config),
    ...(immutable
      ? {
          revalidateIfStale: false,
          revalidateOnFocus: false,
          revalidateOnReconnect: false,
        }
      : {}),
    ...queryOptions,
  });
}
