/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import useSWR from "swr";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../lib/client";
import type {
  GetBoardsIdQueryResponse,
  GetBoardsIdPathParams,
  GetBoardsIdQueryParams,
} from "../../models/GetBoardsId";
import { getBoardsId } from "../../clients/getBoardsId";

export const getBoardsIdQueryKey = (
  id: GetBoardsIdPathParams["id"],
  params?: GetBoardsIdQueryParams,
) => [{ url: "/boards/:id", params: { id: id } }, ...(params ? [params] : [])] as const;

export type GetBoardsIdQueryKey = ReturnType<typeof getBoardsIdQueryKey>;

export function getBoardsIdQueryOptions(
  id: GetBoardsIdPathParams["id"],
  params?: GetBoardsIdQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  return {
    fetcher: async () => {
      return getBoardsId(id, params, config);
    },
  };
}

/**
 * @description /boards/:id operation on board resource
 * {@link /boards/:id}
 */
export function useGetBoardsId(
  id: GetBoardsIdPathParams["id"],
  params?: GetBoardsIdQueryParams,
  options: {
    query?: Parameters<typeof useSWR<GetBoardsIdQueryResponse, ResponseErrorConfig<Error>>>[2];
    client?: Partial<RequestConfig> & { client?: Client };
    shouldFetch?: boolean;
    immutable?: boolean;
  } = {},
) {
  const { query: queryOptions, client: config = {}, shouldFetch = true, immutable } = options ?? {};

  const queryKey = getBoardsIdQueryKey(id, params);

  return useSWR<GetBoardsIdQueryResponse, ResponseErrorConfig<Error>, GetBoardsIdQueryKey | null>(
    shouldFetch ? queryKey : null,
    {
      ...getBoardsIdQueryOptions(id, params, config),
      ...(immutable
        ? {
            revalidateIfStale: false,
            revalidateOnFocus: false,
            revalidateOnReconnect: false,
          }
        : {}),
      ...queryOptions,
    },
  );
}
