/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import useSWRMutation from "swr/mutation";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../lib/client";
import type {
  PatchTodosIdMutationRequest,
  PatchTodosIdMutationResponse,
  PatchTodosIdPathParams,
  PatchTodosIdQueryParams,
} from "../../models/PatchTodosId";
import type { SWRMutationConfiguration } from "swr/mutation";
import { patchTodosId } from "../../clients/patchTodosId";

export const patchTodosIdMutationKey = () => [{ url: "/todos/:id" }] as const;

export type PatchTodosIdMutationKey = ReturnType<typeof patchTodosIdMutationKey>;

/**
 * @description /todos/:id operation on todo resource
 * {@link /todos/:id}
 */
export function usePatchTodosId(
  id: PatchTodosIdPathParams["id"],
  params?: PatchTodosIdQueryParams,
  options: {
    mutation?: SWRMutationConfiguration<
      PatchTodosIdMutationResponse,
      ResponseErrorConfig<Error>,
      PatchTodosIdMutationKey | null,
      PatchTodosIdMutationRequest
    > & { throwOnError?: boolean };
    client?: Partial<RequestConfig<PatchTodosIdMutationRequest>> & {
      client?: Client;
    };
    shouldFetch?: boolean;
  } = {},
) {
  const { mutation: mutationOptions, client: config = {}, shouldFetch = true } = options ?? {};
  const mutationKey = patchTodosIdMutationKey();

  return useSWRMutation<
    PatchTodosIdMutationResponse,
    ResponseErrorConfig<Error>,
    PatchTodosIdMutationKey | null,
    PatchTodosIdMutationRequest
  >(
    shouldFetch ? mutationKey : null,
    async (_url, { arg: data }) => {
      return patchTodosId(id, data, params, config);
    },
    mutationOptions,
  );
}
