/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import useSWRMutation from "swr/mutation";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "../../../lib/client";
import type {
  PostTodosMutationRequest,
  PostTodosMutationResponse,
  PostTodosQueryParams,
} from "../../models/PostTodos";
import type { SWRMutationConfiguration } from "swr/mutation";
import { postTodos } from "../../clients/postTodos";

export const postTodosMutationKey = () => [{ url: "/todos" }] as const;

export type PostTodosMutationKey = ReturnType<typeof postTodosMutationKey>;

/**
 * @description /todos operation on todo resource
 * {@link /todos}
 */
export function usePostTodos(
  params?: PostTodosQueryParams,
  options: {
    mutation?: SWRMutationConfiguration<
      PostTodosMutationResponse,
      ResponseErrorConfig<Error>,
      PostTodosMutationKey | null,
      PostTodosMutationRequest
    > & { throwOnError?: boolean };
    client?: Partial<RequestConfig<PostTodosMutationRequest>> & {
      client?: Client;
    };
    shouldFetch?: boolean;
  } = {},
) {
  const {
    mutation: mutationOptions,
    client: config = {},
    shouldFetch = true,
  } = options ?? {};
  const mutationKey = postTodosMutationKey();

  return useSWRMutation<
    PostTodosMutationResponse,
    ResponseErrorConfig<Error>,
    PostTodosMutationKey | null,
    PostTodosMutationRequest
  >(
    shouldFetch ? mutationKey : null,
    async (_url, { arg: data }) => {
      return postTodos(data, params, config);
    },
    mutationOptions,
  );
}
