/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import useSWRMutation from "swr/mutation";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../../lib/client";
import type {
  PatchBoardsIdMutationRequest,
  PatchBoardsIdMutationResponse,
  PatchBoardsIdPathParams,
  PatchBoardsIdQueryParams,
} from "../../models/PatchBoardsId";
import type { SWRMutationConfiguration } from "swr/mutation";
import { patchBoardsId } from "../../clients/patchBoardsId";

export const patchBoardsIdMutationKey = () => [{ url: "/boards/:id" }] as const;

export type PatchBoardsIdMutationKey = ReturnType<typeof patchBoardsIdMutationKey>;

/**
 * @description /boards/:id operation on board resource
 * {@link /boards/:id}
 */
export function usePatchBoardsId(
  id: PatchBoardsIdPathParams["id"],
  params?: PatchBoardsIdQueryParams,
  options: {
    mutation?: SWRMutationConfiguration<
      PatchBoardsIdMutationResponse,
      ResponseErrorConfig<Error>,
      PatchBoardsIdMutationKey | null,
      PatchBoardsIdMutationRequest
    > & { throwOnError?: boolean };
    client?: Partial<RequestConfig<PatchBoardsIdMutationRequest>> & {
      client?: Client;
    };
    shouldFetch?: boolean;
  } = {},
) {
  const { mutation: mutationOptions, client: config = {}, shouldFetch = true } = options ?? {};
  const mutationKey = patchBoardsIdMutationKey();

  return useSWRMutation<
    PatchBoardsIdMutationResponse,
    ResponseErrorConfig<Error>,
    PatchBoardsIdMutationKey | null,
    PatchBoardsIdMutationRequest
  >(
    shouldFetch ? mutationKey : null,
    async (_url, { arg: data }) => {
      return patchBoardsId(id, data, params, config);
    },
    mutationOptions,
  );
}
